### ISSUE TITLE
Suspicious

### ISSUE THREAD

**Issue by KateKat05** [TwitchRecover/TwitchRecover#104]
im interested in using this, but i am suspicious of its legitimacy. has anyone had any issues or malicious things happen to their computer while using it? and can anyone confirm that it actually functions?

**Comment by m4gnify** [comment]
Works and has worked fine for me the times I've used it.

**Comment by daylamtayari** [comment]
All of the code is open source, and if you don't trust the compiled binaries, you can download the source code and build the program itself.  
  
Also, all of the files of the release have been signed by my PGP key (`EA738D8011BB6318`, the key file can be found by searching for the key on the [openpgp.org keyserver](https://keys.openpgp.org/search?q=EA738D8011BB6318) or on my Github repo hosting all my PGP keys https://github.com/daylamtayari/PGP-Keys).   
On top of that, the file hashes of all of the binaries in `MD4`, `MD5`, `MD6-256`, `MD6-512`, `SHA1`, `SHA256`, `SHA512`, `SHA3-512`, `RIPEMD160`, `GOST` and `CRC32` are listed in the checksum file SHASUMS.digest and that too is signed with my PGP key for proof of authenticity.

Additionally, you can scan all of the binaries using your antivirus or using online services like virus total (an extremely well known and trusted service which takes any file and scans it through over 80 separate reputable antiviruses from Bitdefender to Kapersky  to Google.   
  
All of the files from the [latest release](https://github.com/TwitchRecover/TwitchRecover/releases/tag/2.0aH) have being uploaded to virus total and passed all of the antivirus checks as you can see for yourself: 
- `SHASUMS.digest`: https://www.virustotal.com/gui/url/a8f0e1fb8e9d59204dbd6c3d4ce2c76babe5556a9f19ce0163e0f6ba19bbf07d/detection  
- `SHASUMS.digest.sig`: https://www.virustotal.com/gui/url/71d06ef4ba5c66e57ef36a1e6a01b5bcdfd774f22a5105a4fb1b49de412a7072/detection
- `Twitch.Recover.exe`: https://www.virustotal.com/gui/url/b23578b1e6a5136f14074a45bb3a899c0e55a8e8f4a43225cc984bb243cd742f/detection
- `Twitch.Recover.exe.sig`: https://www.virustotal.com/gui/url/6190340c552a7568392d97fc4f422a775301ed111a06f4fd37b1237fba347031/detection
- `Twitch.Recover.jar`: https://www.virustotal.com/gui/url/708577376637250c316e51e8a045b541aeb5566916a04d7461ac87b80c9d43d1/detection
- `Twitch.Recover.jar.sig`: https://www.virustotal.com/gui/url/4fb9841c52991b31efc0db2da47783aaa690c8f9f74e089e92852532482ef09c/detection
- `Twitch.Recover.Setup.exe`: https://www.virustotal.com/gui/url/9f962ff5003f623a31ce67a022dbe0889080bd2790e49c14abb327af465f1939/detection
- `Twitch.Recover.Setup.exe.sig`: https://www.virustotal.com/gui/url/603a4c2afe61148c4d30e5e2bf80d3ebfd2cb64bc193e7e2825cf0e236e8cf9e/detection
- `Source code (zip)`: https://www.virustotal.com/gui/url/f7c62622339e2f29608217ccf2e0b7b7c40f3d9bea19795999e2fecbc591aba2/detection
- `Source code (tar.gz)`: https://www.virustotal.com/gui/url/dbc760213d7ddcc842ee111940798c7dc86127db5dd9c16a3d39b101b4a9c72c/detection

**Comment by daylamtayari** [comment]
Concerning functionality, it is still in alpha so there are bugs and everything, but for the overwhelming part, it does what it says it does.

**Comment by daylamtayari** [comment]
Closing due to lack of any further discussion.
