### ISSUE TITLE
Any way to find out how long download takes? Or could you show percentage at least?

### ISSUE THREAD

**Issue by heansuh** [TwitchRecover/TwitchRecover#105]
I was wondering if there's any way to find out how long it's going to take, or how much I've downloaded a VOD using TwitchRecover.

All I could see is "Downloading... " and it took me about an hour but I couldn't download the VOD.

For let's say 4h VOD at 720p, how long does it take usuallly?

Could you just add a function of how much of percentage of VOD has been downloaded? Even better, maybe you can show download speed as well.

Thank you.

**Comment by daylamtayari** [comment]
How long it takes is entirely based on the speed of your internet but I will be showing the download speed and percentage in the beta, that is already in the works. 
If you have issues downloading a particular VOD please reopen this issue listing the details about the VOD causing the issue.
