### ISSUE TITLE
Able to get some VOD on Twitch Tracker, but no on TwitchRecover

### ISSUE THREAD

**Issue by TCarneiro91** [TwitchRecover/TwitchRecover#11]
So, this streamer was banned on August 13th: mamadotv

And since then i am trying to get his last VOD. On Twitch Tracker is shows that the Stream started on Thu, Aug 13, 09:36 with a duration of 9h18m

TwitchRecover cannot catch the m3u8 ffrom anything i give him. but it's available on TwitchTracker a portion of that VOD (2h46m)

I now that the stream was restarted somewhere between 15h30 to 16h00, but i can't make it work

**Comment by daylamtayari** [comment]
Have you tried inputting the values from Twitch Tracker manually into the program? I am aware that there are some possible occasional issues with direct recovery using the Twitch Tracker URL.

**Comment by daylamtayari** [comment]
Closing the issue since the VOD in question was one that was over 6 months old.
