### ISSUE TITLE
Program crashes when i try to download a old VOD

### ISSUE THREAD

**Issue by TCarneiro91** [TwitchRecover/TwitchRecover#14]
Hey, when i try to download an old vod, choosing "Recover VOD" the program simply crashes

ex: 

https://user-images.githubusercontent.com/17798233/104375983-2f8ac180-551c-11eb-9157-7ac923e53d75.mp4

**Comment by daylamtayari** [comment]
After testing, if the VOD is unavailable (i.e. too old, removed, etc.), it will simply throw an error causing the program to crash.

**Comment by daylamtayari** [comment]
This will be fixed in the beta version as this is not a critical bug that does not deserve its own hotfix but still an important one that will be fixed in the beta release.

**Comment by daylamtayari** [comment]
Since I am going to have to issue a hotfix for the alpha following Twitch deleting two APIs which were fundamental, this fix will be integrated in that hotfix.

**Comment by daylamtayari** [comment]
Issue has been fixed in commit 198e422c2e83c5b2a919b68bba47a84904013908.
https://github.com/TwitchRecover/TwitchRecover/commit/198e422c2e83c5b2a919b68bba47a84904013908

Will be merged into the main branch and released with the 2.0aH release.

**Comment by Coldblackice** [comment]
Unless I'm mistaken, I believe this is happening again. I get repeated crash-outs and have to restart. It doesn't happen for all channels/VODs.

**Comment by MJCyberCitizen** [comment]
> Unless I'm mistaken, I believe this is happening again. I get repeated crash-outs and have to restart. It doesn't happen for all channels/VODs.

Agreed, also having the same issue trying to download a VOD. If I select the option to find the m3u8 then select the download option for https://vod-secure.twitch.tv/e97ff1dab6e21bd18b6c_erinshaylive_40560792507_1645526665/chunked/index-dvr.m3u8 it works ok.

**Comment by PsychoShock** [comment]
This is still broken. The issue was not fix.
