### ISSUE TITLE
The M3U8 Link Just Loads and Loads in VLCs

### ISSUE THREAD

**Issue by baeconic** [TwitchRecover/TwitchRecover#158]
Yesterday I did a special 6 hour stream and it was such a good stream. While I was live my computer decided it needed a driver update. It froze my camera and my mouse, so I updated my driver while live knowing it would restart the live.
After it restarted I guess the whole live got deleted AS I was live because when I stopped all of the footage was gone.
I’ve never felt so defeated as a content creator. I now know I can record my videos myself as I stream that way I can save them, but twitch doesn’t hold videos that have been somehow deleted as you know. Also no, I didn’t break tos or anything, it was just gone. I’ve already reached out to twitch support and they can’t do anything.
So I tried both 2.0 and 1.2 and both options arent working correctly for me :(  For 1.2 it says its in the Twitch Recover folder but when we look for it, the C: address provided is not in there. 
This is the Twitch Tracker Link: https://twitchtracker.com/baeconic/streams/43167392748
This is the file it says its in but doesnt exist: C:\Program Files (x86)\Twitch Recover\https:\dgeft87wbj63p.cloudfront.net\eb06f8e83cff0ebe043f_baeconic_43167392748_1630776017\chunked\index-dvr.avi

With 2.0 it gives me the Url but the VOD just loads and loads. Here is the link it gives me: https://dgeft87wbj63p.cloudfront.net/eb06f8e83cff0ebe043f_baeconic_43167392748_1630776017/360p30/index-dvr.m3u8
We have tried multiple VLCs, DVD players and a Google Chrome extension mentioned in the issue comments.

I really would like to try and reupload the video back onto Twitch, that way I can create my clips and hightlights to move elsewhere. Ive asked everyone I possibly could for assistance, and everybody is having the same issue. Id be in your debt if you could help me get back my wholesome stream :(

**Comment by Liz-chan** [comment]
Here you go baeconic, I was able to download the video and I uploaded it so that you could download it yourself

https://drive.google.com/file/d/1Q2JmTvHG6I7gD_isHtVVz0HIrHeFTsAa/view?usp=sharing

**Comment by Linden10** [comment]
Sorry I just found you replied to me and didn't know you needed help, happy that @Liz-chan was able to help you out sooner though! Thank you Liz-chan for kindly helping baeconic!

**Comment by baeconic** [comment]
> Here you go baeconic, I was able to download the video and I uploaded it so that you could download it yourself
> 
> https://drive.google.com/file/d/1Q2JmTvHG6I7gD_isHtVVz0HIrHeFTsAa/view?usp=sharing

Thank you so much for this! Linden let me know that you took the time out of your day to do this for me! I actually had a friend fix the issue for me so I completely forgot about posting in here. Thank you for taking time out of your day to save my footage, that is super Kind :)
