### ISSUE TITLE
Now crashes when trying to recover a VOD using twitchtracker link

### ISSUE THREAD

**Issue by Sketchydoor** [TwitchRecover/TwitchRecover#159]
Streamcharts has been crashing for a long time and I think we all know about that one. Now, twitchtracker is not working for me too :(

**Comment by xbloodyswordx** [comment]
Hey bro, did you manage to fix the crashing issue ? I am facing the same issue. Can you tell me how can i solve the problem if you know please ?

**Comment by Sketchydoor** [comment]
I gave up on this program time ago bro. It kept crashing on me all the time and it pissed me off.
