### ISSUE TITLE
Can't download vod 

### ISSUE THREAD

**Issue by N3ars** [TwitchRecover/TwitchRecover#16]
Hey there! thanks for the great tool, I have a problem, was trying to download whatever vod sub only (or not) but it crashes at the beginning, the video is available(dont think it is not since the video is very fresh new) and from lirik for example : https://www.twitch.tv/videos/872169629

**Comment by daylamtayari** [comment]
Ok so I looked into this and well this is awkward, but Twitch just nuked the API that got the tokens, like that API has being completely removed.
This API is required since it is what is used to get the token which is a critical part of another Twitch API that is used to get the list of feeds for a particular VOD.

**Comment by daylamtayari** [comment]
So the only work around there is at this point is to use the VOD recovery option, enter the details (or use a link from an analytics website) and then download the retrieved M3U8 using the M3U8 download feature.

**Comment by daylamtayari** [comment]
This removal of those access tokens APIs has broken ALL Twitch video downloaders, including the major ones like Twitch Leecher.

**Comment by daylamtayari** [comment]
It appears that the access token APIs have been removed in favour of Twitch's GQL API. 

I am going to look into if I can retrieve the corresponding hashes of Twitch's GQL API and am going to issue a hotfix for it as soon as I can figure it out, unless Twitch brings the tokens APIs back out/brings it back online.

**Comment by N3ars** [comment]
Wow! That's unfortunate, right in the moment i wanted to use it. Thanks for your investigation and time, i'm just gonna use what you did mention, m3u8 download feature, hope this whole thing is not as bad as you describe it. Wish you good luck!

**Comment by bbreakthrough** [comment]
Not sure if this helps you (or if you've already figured it out) but Streamlink had to address the access token issue as well.
https://github.com/streamlink/streamlink/pull/3344

**Comment by daylamtayari** [comment]
Issue has been fixed in commit `5e0d23d6afbf97bdb0abe951cdd46f7a4c19acd9`.
https://github.com/TwitchRecover/TwitchRecover/commit/5e0d23d6afbf97bdb0abe951cdd46f7a4c19acd9

Will be merged into the main branch and released with the 2.0aH release.

**Comment by N3ars** [comment]
Up, same issue. Can't download sub only vod this time anymore for ex : https://www.twitch.tv/videos/885501385
it crashes
