### ISSUE TITLE
Clip recovery export results sometimes skip asking

### ISSUE THREAD

**Issue by wl03355609** [TwitchRecover/TwitchRecover#17]
In this part
Do you wish to export the results ('y' for yes, 'n' for no)?: y
Please input the file path where to export the results: 
Sometimes it just jumps to the second line or it just ask you if you want to recover another clips
The chances is slim but is there so I guess I have to tell you that
BTW it a good work, I appreciate it very much

**Comment by daylamtayari** [comment]
Thank you very much for letting me know, there will be input fail safes (i.e. only access y or n inputs in this case) in the beta release.
It is something I plan to implement in the beta release but did not have the time to include that in depth for all the possible inputs.

**Comment by daylamtayari** [comment]
Since I am going to have to issue a hotfix for the alpha following Twitch deleting two APIs which were fundamental, this fix will be integrated in that hotfix.

**Comment by daylamtayari** [comment]
Issue has been fixed in commit `d50887467df5081888ad658d4e569e4aeafd6e25`.
https://github.com/TwitchRecover/TwitchRecover/commit/d50887467df5081888ad658d4e569e4aeafd6e25

Will be merged into the main branch and released with the 2.0aH release.
