### ISSUE TITLE
VOD Won't Open in VLC All of a Sudden

### ISSUE THREAD

**Issue by SoulCommodore** [TwitchRecover/TwitchRecover#176]
Hello all. 

Using version 1.2, I managed to recover this VOD: https://twitchtracker.com/soulcommodore/streams/43903031932
I opened the m3u8 file in VLC, and it played fine. 

However, today, the m3u8 file mysteriously stopped working. I get the following error message: "VLC is unable to open the MRL 'https://dgeft87wbj63p.cloudfront.net/f5657d49175c204276b9_soulcommodore_43903031932_1637881135/chunked/index-dvr.m3u8'. Check the log for details."

I downloaded 2.0, and saw that there was the option to download the m3u8 file as an mp4. I decided to give that a go, since I still have the m3u8 file. But it seems that didn't work either. It says the video has been downloaded, but no file exists in the folder I pointed it to. 

Here is the m3u8 file: https://dgeft87wbj63p.cloudfront.net/f5657d49175c204276b9_soulcommodore_43903031932_1637881135/chunked/index-dvr.m3u8

If anyone could offer help, it would be greatly appreciated. The VOD was only from the 25th of November, well within the 60 days. 

Thank you!

**Comment by swent** [comment]
It seems the files have been deleted from twitch servers.
I don't think anything can be done.

Recovering is a very uncertain task, lately it seems that many VODs get deleted rather sooner than after the usual 60 days.

**Comment by SoulCommodore** [comment]
> It seems the files have been deleted from twitch servers. I don't think anything can be done.
> 
> Recovering is a very uncertain task, lately it seems that many VODs get deleted rather sooner than after the usual 60 days.

Ah okay, that's what I was afraid of. 

Thank you for trying it out, though. I do appreciate it.
