### ISSUE TITLE
Exception in thread "main" error occurs

### ISSUE THREAD

**Issue by kane0303** [TwitchRecover/TwitchRecover#19]
It is assumed that this happens if the streamer's ID include _(underbar)

test)

https://user-images.githubusercontent.com/77548603/104820122-3005be00-5876-11eb-9b44-153e0d59d187.mp4

https://user-images.githubusercontent.com/77548603/104820136-401d9d80-5876-11eb-9910-0b64fbe0e589.mp4

https://user-images.githubusercontent.com/77548603/104820161-62afb680-5876-11eb-997b-bccfad8889eb.mp4

**Comment by daylamtayari** [comment]
After investigation, I forgot to include an underscore in the regex parsing of the stream analytics URLs.

**Comment by daylamtayari** [comment]
Thank you very much for reporting this bug and this will be fixed in the 2.0aH, the alpha hotfix which will be fixing the API change from Twitch and some other minor bugs.

**Comment by daylamtayari** [comment]
Issue has been fixed in commit `9599de9e03dd8ab82def0bf91ac6214648003d93`.
https://github.com/TwitchRecover/TwitchRecover/commit/9599de9e03dd8ab82def0bf91ac6214648003d93

Will be merged into the main branch and released with the 2.0aH release.
