### ISSUE TITLE
5. Recover a VOD streamscharts issue

### ISSUE THREAD

**Issue by Drimon99** [TwitchRecover/TwitchRecover#197]
twitchtracker works:
https://twitchtracker.com/[name]/streams/[ID]
but if i try to use streamscharts for the same stream, it doesn't find the vod "The VOD cannot be found on Twitch servers."
https://streamscharts.com/channels/[name]/streams/[ID]

I would like to use the links of streamscharts, because it splits links when there are multiple streams in the same day (or streaming crashes and resumes immediately), while twitchtracker shows you only the first stream id.
Is there any other way to recover a VOD (get the m3u8 url) without the id (https://www.twitch.tv/videos/[ID])?
Does streamscharts work for you?

**Comment by KaMyKaSii** [comment]
If you use Linux I made a shell script and it works with twitchtracker and streamscharts links. The script code is pretty bad as I'm new to this but what matters is that it works.
[get-vod.zip](https://github.com/TwitchRecover/TwitchRecover/files/8191793/get-vod.zip)

**Comment by Drimon99** [comment]
i use windows, but thanks for the reply anyway

**Comment by KaMyKaSii** [comment]
> i use windows, but thanks for the reply anyway

So in your case I recommend that you use the Twitch Vod Recover option to enter the values ​​manually. Streamer name and VOD ID you can get it easily. To find the stream timestamp, when entering the desired page in streamcharts, type CTRL U to open the source code of the page, then CTRL F and search for the date of the start of the stream in the format YYYY-MM-DD HH:MM:SS and copy the first date you find in that format.

**Comment by Drimon99** [comment]
obviously as written previously with the twitchtracker link it works (https://twitchtracker.com/jakenbakelive/streams/45739914269)
and I get the url (https://d1m7jfoe9zdc1j.cloudfront.net/fb1623fe5d3ea2790f8b_jakenbakelive_45739914269_1646453895/chunked/index-dvr.m3u8)

**Comment by Drimon99** [comment]
Resolved

**Comment by Drimon99** [comment]
its the last version that creates problems

**Comment by rama38** [comment]
> 

So which version are you using right now? 
I am having the same issue, twitchtracker works yet streamcharts doesn't (and I want to use streamcharts with the same reasoning as yours)

I tried both 2.0a Hotfix and 2.0 Alpha (.jar because I'm on Ubuntu) and get the same error.
CLI 1.2 only support TwitchTracker link

**Comment by ItIckeYd** [comment]
@rama38  You can use my repository to recover vods or if you had a particular vod there are many people on here basically just retrieving vods for people as they request. I wouldn't call any of the current versions of the twitchrecover application stable at the moment but it works in some cases and could be updated in the future.

**Comment by rama38** [comment]
> @rama38 You can use my repository (python script) to recover vods or if you had a particular vod there are many people on here basically just retrieving vods for people as they request. I wouldn't call any of the current versions of the twitchrecover application stable at the moment but it works in some cases and could be updated in the future.

Oh yes! I just started using yours right now. Found it while searching here.
Finally figured it out that I need to add my timezone to the stream start time, I was confused for the longest time because TwitchRecover find a VoD yet yours didn't.

I don't really understand how the unmute works though? So the script detected muted segments and it asks if I want to unmuted and I chose yes and it created an .m3u8 file

**Comment by ItIckeYd** [comment]
@rama38 unmuting a vod allows for a muted vod to be played.. if you try playing a muting vod the segments that are muted will make the vod crash and not playable.
