### ISSUE TITLE
URLs not starting in https don't work

### ISSUE THREAD

**Issue by daylamtayari** [TwitchRecover/TwitchRecover#2]
Twitch Tracker links that do not start in `https://` do not work.

**Comment by daylamtayari** [comment]
No safeguard for various URL formats which needs to be implemented.

**Comment by daylamtayari** [comment]
This is caused by an issue of using the HttpURLConnection class which is restricted to JDK 14 and above while this program should be compatible for JDK 8.

**Comment by daylamtayari** [comment]
This issue has now been fixed with #4 
This issue shall now be closed.

**Comment by s014248** [comment]
When I try to download the following VOD: https://www.twitch.tv/videos/657504247, it says there's an exception and the program crashes. Does it not work with VODs more than 60 days old?

**Comment by daylamtayari** [comment]
@s014248 please next time create an issue but here the reason this VOD is not working is because it currently is not up, you would need to recover it and then download the resulting M3U8. And yes if it is over 60 days unless it is from certain twitch esport partners they wont be recoverable.
