### ISSUE TITLE
Recover VODs option does not work

### ISSUE THREAD

**Issue by GutHib1209** [TwitchRecover/TwitchRecover#200]
Recover a VOD, with both stream analytics links and input values manually, causes the the program to suddenly close.

**Comment by KaMyKaSii** [comment]
Try the release from [this](https://github.com/PaaaulZ/TwitchRecover/releases) repository

**Comment by GutHib1209** [comment]
@KaMyKasii The TwitchRecover release from the repository you linked does not work. 

I reinstalled it and it worked fine. Don't really know why it wasn't working before. At least it's resolved
