### ISSUE TITLE
VOD unable to be downloaded on either 2.0 or 1.2 (please help)

### ISSUE THREAD

**Issue by ColtBolt** [TwitchRecover/TwitchRecover#213]
I've been trying to get https://twitchtracker.com/cyberseiso/streams/46237822797 for over an hour and a half but I can't seem to be able to get it as 1.2 just closes on me when I enter the date or just stalls (I've waited 30 mins while trying out 2.0) , and 2.0 can't seem to find a result.

Am I doing something wrong here? If you can help I'll be really appreciative as this is sedimentally an important stream

**Comment by KaMyKaSii** [comment]
Can you confirm that the stream started at 22 Apr 2022, 09:00:00 UTC? 
And if you're the streamer and you accidentally deleted the stream, apparently Twitch is currently deleting files from their servers (at least the servers we're aware of) right away, so don't get your hopes up.

**Comment by ColtBolt** [comment]
> Can you confirm that the stream started at 22 Apr 2022, 09:00:00 UTC? And if you're the streamer and you accidentally deleted the stream, apparently Twitch is currently deleting files from their servers (at least the servers we're aware of) right away, so don't get your hopes up.

Yes I can confirm it started at  22 Apr 2022, 09:00:00 UTC
I'm not the streamer. The streamer forgot to save the VOD so twitch didn't save it (as you said as Twitch is instantly deleting VODs if the streamer doesn't set the settings correctly from the defualt options) 
Is all hope lost?

**Comment by KaMyKaSii** [comment]
> 

Sadly yes. The streamer needs to enable “Store Past Broadcasts” in the account settings or Twitch will not create any VODs for the stream. Currently VodRecover can only recover the link of VODs automatically deleted by Twitch after the 60 day timeout (the file stays on the server for approximately 3 more days), the link of VODs not published by the streamer and sub only VODs.

**Comment by ColtBolt** [comment]
Ok I see, thank you for your quick reply
