### ISSUE TITLE
TwitchRecover doesn't work

### ISSUE THREAD

**Issue by edsdream** [TwitchRecover/TwitchRecover#222]
https://twitchtracker.com/givemecs/streams/39320596535

I'm in Korea, and I can't recover this VOD.

I need your help, please.

**Comment by ItIckeYd** [comment]
@edsdream 

Streamscharts had the correct start time.. twitchtracker was 15 minutes off.

https://d3vd9lfkzbru3h.cloudfront.net/2ce7d5beec2202f314ce_givemecs_39320608583_1652296620/chunked/index-dvr.m3u8
https://d1mhjrowxxagfy.cloudfront.net/2ce7d5beec2202f314ce_givemecs_39320608583_1652296620/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

**Comment by edsdream** [comment]
@ @ItIckeYd Thank you so much. It's very kind of you.
