### ISSUE TITLE
Clip recovery - possible wfuzz issue

### ISSUE THREAD

**Issue by blackesteagle** [TwitchRecover/TwitchRecover#227]
I've been using a branch of TwitchRecover from user PaaaulZ(who deleted everything a few weeks ago I don't know why), Recover all clips from a stream option was working up till yesterday, It no longer calls wfuzz it seems to me. When I checked wfuzz in CMD I got a few errors. I've deleted/reinstalled everything(python 3.8, pycurl 7.43.0.5, colorama, wfuzz) but still no clip recovery and the same wfuzz error. Anyone have the same issue or any idea how to fix it?

`C:\Users\USERNAME>wfuzz
********************************************************
* Wfuzz 3.1.0 - The Web Fuzzer                         *
*                                                      *
* Version up to 1.4c coded by:                         *
* Christian Martorella (cmartorella@edge-security.com) *
* Carlos del ojo (deepbit@gmail.com)                   *
*                                                      *
* Version 1.4d to 3.1.0 coded by:                      *
* Xavier Mendez (xmendez@edge-security.com)            *
********************************************************

Usage:  wfuzz [options] -z payload,params <url>

        FUZZ, ..., FUZnZ  wherever you put these keywords wfuzz will replace them with the values of the specified payload.
        FUZZ{baseline_value} FUZZ will be replaced by baseline_value. It will be the first request performed and could be used as a base for filtering.

Examples:
        wfuzz -c -z file,users.txt -z file,pass.txt --sc 200 http://www.site.com/log.asp?user=FUZZ&pass=FUZ2Z
        wfuzz -c -z range,1-10 --hc=BBB http://www.site.com/FUZZ{something not there}
        wfuzz --script=robots -z list,robots.txt http://www.webscantest.com/FUZZ

Type wfuzz -h for further information or --help for advanced usage.
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\wfuzz\wfuzz.py", line 44, in main
    session_options = CLParser(sys.argv).parse_cl().compile()
  File "c:\program files\python38\lib\site-packages\wfuzz\ui\console\clparser.py", line 166, in parse_cl
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\wfuzz.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\wfuzz\wfuzz.py", line 93, in main
    Facade().sett.save()
  File "c:\program files\python38\lib\site-packages\wfuzz\helpers\obj_factory.py", line 19, in __call__
    class_.instance = super(Singleton, class_).__call__(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\wfuzz\facade.py", line 72, in __init__
    self.sett = Settings()
  File "c:\program files\python38\lib\site-packages\wfuzz\externals\settings\settings.py", line 22, in __init__
    self.cparser.read(self.filename)
  File "c:\program files\python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\program files\python38\lib\configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\USERNAME\\.config\\wfuzz\\wfuzz.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`

**Comment by ItIckeYd** [comment]
@blackesteagle i believe it’s an issue with your ini file. View it and see if it contains a bunch of garbage characters… If it does simply remove everything in the file and rerun the program.

**Comment by blackesteagle** [comment]
@ItIckeYd Which ini file? Where? I use both releases from this-original TwitchRecover and the one release from PaaaulZ interchangeably depending on which options work on which releases etc but have no ini file for any of the releases. Is it an ini file from python side?
