### ISSUE TITLE
Older Stream IDs -Where to find them?

### ISSUE THREAD

**Issue by blackesteagle** [TwitchRecover/TwitchRecover#230]
I'm using Stream IDs for clip recovery, if a stream has 1 or more disconnects that are quickly recovered StreamsCharts usually creates separate IDs where TwitchTracker doesn't bother in most cases, Therefore using IDs from StreamsCharts ensures you can get most clips from an unstable stream, where as if you are using TwitchTracker IDs its more likely you'll miss out on clips after the first disconnect of a stream even tho you seemingly scan all of its length. The problem is apparently StreamsCharts started its listing since mid 2019 where as TwitchTracker has been listing since mid 2016(Also StreamsCharts IDs are wrong for the first few months): A lot of missing IDs from mid 2016 to late 2019. So is there another site/way listing stream IDs in a more complete way than TwitchTracker/StreamsCharts?

**Comment by ItIckeYd** [comment]
@blackesteagle Use www.sullygnome.com.. clips can be recovered from may 26th, 2016 to present.

**Comment by blackesteagle** [comment]
I just use the Stream IDs in TwitchRecover to list all the clips from a stream, you probably mean recovering specific clips you have a link to? 

Anyway, that site seems to be listing stream IDs in a more complete way  it seems, which was what I was asking so thanks :)

**Comment by ItIckeYd** [comment]
@blackesteagle uh? if a vod is broken up there will be multiple vod id's each would have their own set of clips. No I mean recovering all clips from any stream.

**Comment by blackesteagle** [comment]
@ItIckeYd it looks to me sullygnome site stops listing the "missing IDs" at around the end 2018 and starts listing them identically as TwitchTracker. StreamsCharts starts listing IDs "more completely & accurately at around the beginning of November. Most "missing IDs" from 2019 are still missing, oh well :)

**Comment by ItIckeYd** [comment]
@blackesteagle possibly.. no idea. As of right now I don't know of any other analytical sites that track that information. Although if someone used twitch api the information is probably there.
