### ISSUE TITLE
Empty index-dvs files (normal?) 

### ISSUE THREAD

**Issue by MgWild14** [TwitchRecover/TwitchRecover#237]
Hey its me again, I'm sorry to bother you but I have another problem. 

So I used to have a problem with using twitch.recover and then with how to read m3u8 files and you fixed both but now I have another problem 😁

Sooo, now my problem is that the m3u8 files that I get from the T.R url are all empty files (20ko) instead of the ones I got from you from another post where you helped me (5-15go), actually there is one that's from me idk how I did it during the week, I really don't know. 
And so I can't do anything with them, I can't convert or download them, I can't even read them. 
I've tried for at least 10hours this week and now idk what to do.. 

I'm wondering if there aren't muted segments but I don't know how to check if there are or even how to unmute them. 
I've seen you gave people python links but I'm a total noob at coding. 

These are the streams I want to download if you want to check the segments or help me directly 💕: 

1 - https://twitchtracker.com/heisuten/streams/46460678829

2 - https://twitchtracker.com/heisuten/streams/46471123261

3- https://twitchtracker.com/heisuten/streams/46484311933

4- https://twitchtracker.com/heisuten/streams/46492563325

5-(bonus)
https://twitchtracker.com/heisuten/streams/46320871693

Please be my angel again ❤️🙏😇
Also I had to remake this post since it seems like it didn't post itself (Yes, FML 💀💀💀)

**Comment by ItIckeYd** [comment]
@MgWild14 

https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/index-dvr.m3u8
Vod contains muted segments

https://d1m7jfoe9zdc1j.cloudfront.net/c79d1dc2f3042c4419aa_heisuten_46471123261_1653507921/chunked/index-dvr.m3u8
Vod contains muted segments

https://d1m7jfoe9zdc1j.cloudfront.net/5a35b3e30b5c7a51e440_heisuten_46484311933_1653686472/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

https://d1m7jfoe9zdc1j.cloudfront.net/aa550ff52bd20700e926_heisuten_46492563325_1653785113/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

https://d1m7jfoe9zdc1j.cloudfront.net/1824a98a104230e975b9_heisuten_46320871693_1651514155/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

Use twitchrecover to unmute the ones that say 'Vod contains muted segments' but they all work.

**Comment by MgWild14** [comment]
Should I be seeing them in the folder of the FILE PATH they are asking me? Because I see nothing new, I've tried both link and file

**Comment by ItIckeYd** [comment]
@MgWild14 it should ask you to input the m3u8 link then a path where you want to save it.

It works for me.

**Comment by MgWild14** [comment]
It also works for me!! Thank you so much!!
😍😍✨✨
I'll close this tomorrow tho after I make sure everything is set.
have a nice day man

**Comment by 1ceSpir1t** [comment]
Hello, I was looking around some issues regarding this code because I also been having some and results that you are having the same issues as I am and I was coming to ask ItlckeYd if he could help me get the m3u8 for a stream of mine if it was possible. I have 3 streams I would love to get acess to again but I cant atm as I am having the same issues to the point I dont know what to do anymore but ask for help. Here are the TwitchTracker Links:

#1 - https://twitchtracker.com/abeelxo/streams/45355021388
#2 - https://twitchtracker.com/abeelxo/streams/45351191868
#3 - https://twitchtracker.com/abeelxo/streams/39365318232

Please I would really appreciate it if I can get some help here. Thank you

**Comment by MgWild14** [comment]
R. I. P iceSpirit 😥 

Also my problem was actually common I was just dumb and thought it had to do with the size of the files but no. (should probably change title to hi I'm dumb) 

Itickles I have another problem tho, the unmuted m3u8 files that I got from option n°10 are not readable and I can't convert them like the others.
 
Could you tell me what to type in the " Find and Replace" thing in notepad for "search" and "replace with" (if that's the thing to do)

**Comment by MgWild14** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#ID3-EQUIV-TDTG:2022-05-24T02:53:37
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:0.000
#EXT-X-TWITCH-TOTAL-SECS:8720.968
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/0-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/1-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/2-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/3-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/4-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/5-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/6-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/7-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/8-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/9-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/10-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/11-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/12-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/13-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/14-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/15-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/16-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/17-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/18-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/19-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/20-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/21-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/22-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/23-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/24-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/25-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/26-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/27-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/28-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/29-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/30-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/31-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/32-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/33-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/34-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/35-muted.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/36.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/37.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/38.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/39.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/40.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/41.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/42.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/43.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/44.ts
#EXTINF:10.000,
https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/45.ts

**Comment by ItIckeYd** [comment]
@MgWild14 What are you using to convert and what type of file are you converting into? 

I'm able to get it to start downloading using option 11 of twitchrecover then option 3 to convert to MP4.

**Comment by MgWild14** [comment]
You'd think i would've checked them by now since that's what got me into trouble in the first place but no, thats how STUPID i am. 
I'm using VideoProc Converter and i probably gave my pc walwares for that lol.
i'm having trouble with this, is option 11+3 for the ones that dont need to be unmuted and option 12 for the one that i did unmute or is it all for the ones that need to be unmuted

**Comment by MgWild14** [comment]
What do they mean by .ts files , all the files i get are M3U8 and they look like VLC files

**Comment by ItIckeYd** [comment]
@MgWild14 when you open a M3U8 file in notepad++ it is made up of .TS files.. those .TS files are the segments i'm checking when I say number of segments is valid vs invalid. If i'm not wrong you should be able to convert/download the M3U8 link even if it has muted segments although I don't think twitchrecover has functionality to take a file path and convert a local M3U8 file.. you may have to use another application for that. 

TwitchRecover asks for a link specifically like - https://d1m7jfoe9zdc1j.cloudfront.net/6539ac4502cc44f519b9_heisuten_46460678829_1653352090/chunked/index-dvr.m3u8 not a file path.

I'd have to look through the code again to see if it unmutes the file before it downloads it... otherwise the muted segments probably won't be playable when the file is downloaded if it is even downloadable when muted.

**Comment by MgWild14** [comment]
I think thats why when i give him the path of unmuted files it just closes.

1 - "If i'm not wrong you should be able to convert/download the M3U8 link even if it has muted segments althou" You mean with option 11? I've just tried but it closes as well. 
If you were talking about downloading from pasting into browser yes i can but i personally cant do anything with it later (convert, read, ..)

 ... " otherwise the muted segments probably won't be playable when the file is downloaded if it is even downloadable when muted." yeaah

so i might want to look out for app that create links of M3U8 out of M3U8 files right? (if yes do you have any suggestion)

You've already helped me so much man , now i get to see most of the streams i missed and this is a lifechanger. You can take as much time as you want i will not complain lol!
