### ISSUE TITLE
I installed the recoverer but it doesn't work

### ISSUE THREAD

**Issue by jeremia314** [TwitchRecover/TwitchRecover#25]
I installed the recoverer as soon as i type in the values, the prompt closes automatically.

**Comment by jeremia314** [comment]
ah i saw the issue tab.

**Comment by daylamtayari** [comment]
Could you elaborate on your issue or have you been able to fix it?

**Comment by jeremia314** [comment]
did it on the new issue tab https://github.com/siddhantdubey/getdeletedtwitchvods/issues/7

**Comment by daylamtayari** [comment]
So I understand you are trying to recover this VOD right? `https://twitchtracker.com/wkgml/streams/40201692781`
For some reason I am not getting any results so let me look into this and try and see why, first time I am unable to recover a stream that is barely a couple days old so let me look into this and try and see why thats the case.

**Comment by daylamtayari** [comment]
@jeremia314 Do you know if this streamer saves her VODs?
Because if she has VODs disabled, you wont be able to recover the VOD since there is no VOD that is made/that exists.
