### ISSUE TITLE
Mac fails to run

### ISSUE THREAD

**Issue by tomg55555** [TwitchRecover/TwitchRecover#253]
Hello! I've downloaded jar file on 1.2 and also tried 2.0 version but I am unable to run it and I do not understand why. I have Java installed. Someone has same issue or have a solution? Thanks in advance

**Comment by tomg55555** [comment]
error msg is "check consolle for possible error messages" but none appears in consolle

**Comment by tomg55555** [comment]
figured it out, to launch it you need to go to terminal and run it with
 `$ java -jar ~/Downloads/TwitchRecover.jar`

**Comment by JupitersClaim** [comment]
Can you help me? I'm having a similar issue. I've installed Java, downloaded the 2.0 version (.jar file) but can't launch the program. Even when I use the terminal command you have here, I still get an error message.
