### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by dverma1232** [TwitchRecover/TwitchRecover#256]
Trying to get recover this VOD: https://twitchtracker.com/adinross/streams/46580883325 but it just fails without an error.
Would appreciate any help. Thanks

**Comment by ItIckeYd** [comment]
@dverma1232 

https://d1m7jfoe9zdc1j.cloudfront.net/b2c77dedbf6647709a1f_adinross_46580883325_1654930427/chunked/index-dvr.m3u8
Vod contains muted segments

**Comment by dverma1232** [comment]
Thanks!
By the way, how did you manage to get it? I tried your repo as well and it returned no results.

**Comment by ItIckeYd** [comment]
@dverma1232 my script requires local timezone to be inputted as start time....

Example:
Vod Time: Sat, Jun 11, 06:53 - UTC
vs
Vod Time (My time):  Sat, Jun 11, 03:53 - UTC-3
