### ISSUE TITLE
Strange behavior when recovering a VOD

### ISSUE THREAD

**Issue by Liwyght** [TwitchRecover/TwitchRecover#259]
Greetings

I'm trying to recover a VOD

But when TwitchRecover finds it, it only finds a .m3u8 vod which lasts 3hs. It is indeed the beginning of the stream, but the stream lasted around 12-13hs

I've noticed Twitch has separated the stream into 3 parts, 1st = 3hs, 2nd = 1h and the 3rd part is gone (which would have the remaining 8-9hs)

I have tried forcing TwitchRecover by inputting the time myself but I can't get any result out of it. And Stream Charts links crash TwitchRecover instantly

Any advice/help would be appreciated, thanks!

**Comment by Soapzz** [comment]
Send me the links of the VODs you were trying to recover using streamscharts.com

When a stream gets cut and relaunched twitchtracker sometimes only show the first part so Streamcharts is always better for me

Don't try to recover them with TwitchRecover using manual input or Streamcharts links, the program will crash, just send me the links you got from Streamcharts and I'll look at it for you

**Comment by Liwyght** [comment]
Could you explain to me how to download the VOD with Streamcharts? I'd give you the VOD but it has been removed already from Twitch servers so I can't get the m3u8. (I know this because I have tried multiple times with TwitchTracker hoping to the skies for this issue to fix itself lol, did I ever tell you the definition of insanity?)

**Comment by Soapzz** [comment]
I recover VODs using this :

https://github.com/ItIckeYd/VodRecovery

But it's a real pain to get it to work, I don't even remember how I got it to work, you need to use something called Python, and if you're new to it like me then good luck.

Do you still have the TwitchTracker link to the first part of the VOD, first part of the stream may be deleted but that doesn't mean all the parts are gone, I can look for the other parts of the stream myself

**Comment by Liwyght** [comment]
Thanks for the info! Yeah I'm pretty ignorant in all of this to be honest, so it's gonna be a difficult task for me

The VOD is distributed throughout the following links:

-TwitchTracker: https://twitchtracker.com/kurlyrose/streams/39523990664

-StreamCharts: 
https://streamscharts.com/channels/kurlyrose/streams/39523990664
https://streamscharts.com/channels/kurlyrose/streams/39524036920
https://streamscharts.com/channels/kurlyrose/streams/39525523480

(These 3 are all the same stream, but Stream Charts separated it in 3 parts)

Thanks again for your help

**Comment by Soapzz** [comment]
Hi, sorry to bring this to you but all 3 parts of this stream have been deleted entirely from Twitch servers and can't be recovered.
If you need help with recovering another one of those multiple parts VODs in the future, feel free to write me here, I'll look at it for you.
Have a great day/night.
