### ISSUE TITLE
Twitch recoverer failed to download because a virus was found

### ISSUE THREAD

**Issue by jeremia314** [TwitchRecover/TwitchRecover#26]
what

**Comment by daylamtayari** [comment]
This must be a false positive from your antivirus.

**Comment by daylamtayari** [comment]
As proof here is a virustotal scan of the setup file: https://www.virustotal.com/gui/url/9f962ff5003f623a31ce67a022dbe0889080bd2790e49c14abb327af465f1939/detection

and I am uploading the other files as we talk

**Comment by daylamtayari** [comment]
Setup executable - https://www.virustotal.com/gui/url/9f962ff5003f623a31ce67a022dbe0889080bd2790e49c14abb327af465f1939/detection  
Executable - https://www.virustotal.com/gui/url/b23578b1e6a5136f14074a45bb3a899c0e55a8e8f4a43225cc984bb243cd742f/detection   
Jar - https://www.virustotal.com/gui/url/708577376637250c316e51e8a045b541aeb5566916a04d7461ac87b80c9d43d1/detection

**As you can see all have been labeled as clean by every antivirus.**

**Comment by daylamtayari** [comment]
Closing the issue as clearly none of the files contain any malicious files.
