### ISSUE TITLE
NO SUCCESSFUL RESULTS WERE FOUND (1.2)

### ISSUE THREAD

**Issue by maymay112** [TwitchRecover/TwitchRecover#262]
When inputting twitchtracker stream URLs for m3u8 links, the titled error occurs.

https://twitchtracker.com/criticalrole/streams/40885972155

;is the stream link I'm using

I've attempted to use links from the channel's previous streams too from the past month to see if this stream in particular was problematic, but the same error keeps occurring. It's odder because I've had no issues with downloading those exact streams for months now (all within a few hours of them ending), but suddenly they've all stopped working for some reason.

**Comment by Soapzz** [comment]
https://dqrpb9wgowsf5.cloudfront.net/b5838164fd6b39b34b7b_criticalrole_40885972155_1655430314/chunked/index-dvr.m3u8
