### ISSUE TITLE
why stream charts links not working for recover?

### ISSUE THREAD

**Issue by wnase** [TwitchRecover/TwitchRecover#267]
The program shuts down as soon as I put a stream charts link to recover a vod, the link that i'm trying to put is : https://streamscharts.com/channels/wsh_tv/streams/45471716172

**Comment by ItIckeYd** [comment]
@wnase application uses deprecated  streamscharts api therefore it will not work.

**Comment by wnase** [comment]
thanks for your answer, the problem with twitch tracker is when the streamer cuts and restarts right after, it only takes into account the first replay unlike stream charts, too bad.

**Comment by ItIckeYd** [comment]
@wnase 

https://d1ymi26ma8va5x.cloudfront.net/4441421b672edeed7e7a_wsh_tv_45471716172_1653587705/chunked/index-dvr.m3u8
Vod contains muted segments
Total Number of Segments: 3035
Would you like to check if segments are valid (Y/N): y
3035 of 3035 segments are valid.

You will have to unmute vod with twitchrecover.

**Comment by wnase** [comment]
thank you so much! have a nice day

**Comment by botcoder-sys** [comment]
@ItIckeYd I tried unmuting a m3u link via using 10th option but it is still giving me the same video length of small cut. Please let me know if I am doing something wrong.

**Comment by ItIckeYd** [comment]
@botcoder-sys vod is probably split up into multiple different broadcasts aka streamer restarted the stream. Might be able to find the other part of the vod on streamscharts as it usually gets all instances of any stream.

**Comment by SquiddGame** [comment]
Im having the same issue here, any fix ? 
The problem with twitch tracker is that it counts the restarted stream as one whereas on streamscharts all the restarted stream are separated. 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/106984250/176745238-e934b891-c2e9-4716-8183-60aca4091c16.png">
<img width="105" alt="image" src="https://user-images.githubusercontent.com/106984250/176745347-2e5735a5-701e-4859-8c89-e27e5a5c156a.png">
