### ISSUE TITLE
Streamscharts doesn't work

### ISSUE THREAD

**Issue by sumlynx** [TwitchRecover/TwitchRecover#269]
I want to recover a VOD, but I can't use TwitchTracker because the streamer cut and restarted their stream immediately, so it registers both streams as one link. Streamscharts has the correct link, but TwitchRecover crashes when I input it. Is there a way to fix this, or another way to recover the VOD?

https://streamscharts.com/channels/dunrunnin12/streams/46691586349

**Comment by Soapzz** [comment]
https://d1m7jfoe9zdc1j.cloudfront.net/f77b0178e7831ca29b36_dunrunnin12_46691586349_1656296571/chunked/index-dvr.m3u8

**Comment by Soapzz** [comment]
Using this other thing :

https://github.com/ItIckeYd/VodRecovery

But it's a pain in this ass to get it working, I don't even remember how I managed to do it.
Here is your link, enjoy :

https://d1ymi26ma8va5x.cloudfront.net/94c6b63ccbdf9558f9c5_koumoo_45678625196_1656532490/chunked/index-dvr.m3u8

**Comment by sumlynx** [comment]
@Soapzz Thanks for your help, I appreciate it.
