### ISSUE TITLE
VOD request

### ISSUE THREAD

**Issue by biiilll** [TwitchRecover/TwitchRecover#271]
Trying to get recover this VOD : 

https://twitchtracker.com/hjy0410/streams/39440733687
https://twitchtracker.com/hjy0410/streams/45921223085

Please..

**Comment by Soapzz** [comment]
June 26 VOD is in two parts :
Part 1 - https://d3vd9lfkzbru3h.cloudfront.net/67c09b56cfc4ef38ed37_hjy0410_39440733687_1656255651/chunked/index-dvr.m3u8
Part 2 - https://d3vd9lfkzbru3h.cloudfront.net/6bfe45a286150bf28d59_hjy0410_39440822247_1656257901/chunked/index-dvr.m3u8

March 21 VOD is too old, can't be recovered
