### ISSUE TITLE
No Sucessful Results VOD request 

### ISSUE THREAD

**Issue by Lonewolfonmove** [TwitchRecover/TwitchRecover#281]

**Comment by Soapzz** [comment]
Hi, 
This VOD have been entirely deleted from Twitch servers, sorry.

Have a good day.

**Comment by Lonewolfonmove** [comment]
Hi, 

Would you be able to restore this stream by any chance? I know the odds are less, but it would be great if you could try it.

https://streamscharts.com/channels/noxflight/streams/46218103949
