### ISSUE TITLE
need help for a vod  thanks

### ISSUE THREAD

**Issue by Redfly020** [TwitchRecover/TwitchRecover#291]
https://twitchtracker.com/aloonea/streams/45739209404

**Comment by ItIckeYd** [comment]
@Redfly020 

https://d1ymi26ma8va5x.cloudfront.net/e3eac56b2c97cb22099d_aloonea_45739209404_1657545019/chunked/index-dvr.m3u8

**Comment by Redfly020** [comment]
thanks and this plz https://twitchtracker.com/evalunna/streams/45820710380
