### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by yelloweyedd** [TwitchRecover/TwitchRecover#315]
Hello! Its Sub Only VOD its not deleted but i cant recover. Can you help?

https://twitchtracker.com/swaggybark/streams/39748364856
https://streamscharts.com/channels/swaggybark/streams/39748364856

**Comment by ItIckeYd** [comment]
@yelloweyedd 

https://dgeft87wbj63p.cloudfront.net/575443950d49b0ac2f74_swaggybark_39748364856_1661118351/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
