### ISSUE TITLE
Clip recovery is broken

### ISSUE THREAD

**Issue by TCarneiro91** [TwitchRecover/TwitchRecover#32]
What the title says, when i put the twitchtracker link to recover all clips from a stream the program just crashes

**Comment by daylamtayari** [comment]
Clip recovery is indeed broken for Twitch Tracker links. 
In the meantime please use a Streamscharts link or input the value manually.

This will be fixed for the 2.0b release.

**Comment by daylamtayari** [comment]
Issue has been inadvertently fixed in commit `bca901d45313532a62e554384c1a86f73975cde1`.
https://github.com/TwitchRecover/TwitchRecover/commit/bca901d45313532a62e554384c1a86f73975cde1

Will be merged into the main branch and released with the 2.0b release.
