### ISSUE TITLE
help old vod

### ISSUE THREAD

**Issue by wnase** [TwitchRecover/TwitchRecover#326]
Is it possible to recover old vod? If so does someone has a script that can recover them

**Comment by ItIckeYd** [comment]
@wnase It depends on what you consider old? Threshold is usually max 60 days... sometimes less sometimes more.

**Comment by KaMyKaSii** [comment]
VODs deleted by the streamer themselves currently start being deleted by the server immediately after the streamer requests it. It is very difficult to recover a VOD deleted by the streamer, it is usually possible to just partially recover it if you try to recover it in a matter of a few minutes (in rare exceptions a few hours) after the deletion request is made. Successful retrievals are in cases of unpublished VODs (either by the action of the streamer or by Twitch after mutating the VOD and auto unpublish it). The "60 day limit" issue is only for recovering VODs with the time of life reached and automatically deleted by Twitch itself. They are first removed from the streamer's public page but are usually only deleted 2 days later (62 days old), but I've seen VODs still recoverable at 74 days old.

**Comment by wnase** [comment]
thanks
