### ISSUE TITLE
VOD Recover

### ISSUE THREAD

**Issue by davidhinazuki** [TwitchRecover/TwitchRecover#332]
I want to recover a VOD from twitch: https://twitchtracker.com/letstaddl/streams/39782599784
It gives me a link: https://dgeft87wbj63p.cloudfront.net/c299a1469cf7976b69b3_letstaddl_39782599784_1662192991/720p60/index-dvr.m3u8
but it doesnt play in vlc. did i do smth wrong? I would really appreciate it if you could help me.

**Comment by KaMyKaSii** [comment]
You always need to check if the VOD is muted and then unmute it if necessary. Anyway, here is the "unmuted" link:
http://sprunge.us/XAEXYe
