### ISSUE TITLE
VOD Recover : No successful results were found

### ISSUE THREAD

**Issue by Frenchy872** [TwitchRecover/TwitchRecover#338]
I've been trying to recover this deleted VOD link : https://twitchtracker.com/capassotriplets/streams/47125537677
But no successful results were found, is anyone could help me ?
Thank you

**Comment by ItIckeYd** [comment]
@Frenchy872 
https://d2vjef5jvl6bfs.cloudfront.net/d995172909cf94bdd099_capassotriplets_47125537677_1662841803/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

**Comment by Frenchy872** [comment]
Thank you so much for your help !
