### ISSUE TITLE
In Version 2.0, can you get M3U8 links from twitch tracker?

### ISSUE THREAD

**Issue by Adroxxx** [TwitchRecover/TwitchRecover#35]
Hi, 

Is there a way to use twitch tracker links of a streamer in order to get m3u8 links in TwitchRecover version 2.0? 
Sometimes the vods are being deleted from twitch, so you have to use twitch tracker to get the VOD links.

I have to use version 1.2 to export the generated m3u8 links and then download the m3u8 VOD (command 11) with the version 2.0.

**Comment by daylamtayari** [comment]
Sorry just saw this but you are able to use twitch tracker links in the 2.0a version to get the M3U8 link.
As you said there has been a few reports of it not working but those have been extremely few, less than a handful.

**Comment by Adroxxx** [comment]
How do you get the M3U8 link in the new 2.0a version? It says the stream has to be live to get it. 

I want to use twitch tracker, however.
