### ISSUE TITLE
Twitch Leecher is discontinued

### ISSUE THREAD

**Issue by Franiac** [TwitchRecover/TwitchRecover#350]
@daylamtayari Since my name pops up in your Credits, you know who I am. I just want to leave the info here that a whole lot of people may fall into your front door in the next couple of weeks since I discontinued Twitch Leecher.

[More info here](https://github.com/Franiac/TwitchLeecher/issues/803)

Wish you all the best

~ Franiac

**Comment by daylamtayari** [comment]
Hey @Franiac , thanks for all of the work you put into Twitch Leecher.

Thank you very much for the heads up! Rebuilding it from scratch rn so going to try and get it done faster now that I know there is going to be a big influx on people.

I did want to touch on the GraphQL API comment, I personally discovered it through seeing other projects utilising it and while I am aware its not a publicly supported API, I haven't ever seen Twitch make an outright statement on its use and the fact that hundreds if not thousands of projects utilise it makes it seem that they fully tolerate its use.

Congratulations on your daughter, wish you the best!
