### ISSUE TITLE
VOD recovery request

### ISSUE THREAD

**Issue by Fortishan** [TwitchRecover/TwitchRecover#354]
Please help me with this. Thanks! 
 
https://twitchtracker.com/swaggybark/streams/39905733112
https://streamscharts.com/channels/swaggybark/streams/39905733112

**Comment by Fzxselfcn** [comment]
https://dgeft87wbj63p.cloudfront.net/31b400c294a12d3b1ead_swaggybark_39905733112_1664828047/chunked/index-dvr.m3u8
İyi seyirler :)

**Comment by Fortishan** [comment]
Saolasın ❤️
