### ISSUE TITLE
M3u8 not playing in vlc

### ISSUE THREAD

**Issue by CluelessToaster** [TwitchRecover/TwitchRecover#369]
when i try to play the m3u8 in vlc it shows the duration but won't play. I checked if there were any muted segments and there was not. 
https://vod-secure.twitch.tv/835e383e4a7bd8676728_ikitty_41427938603_1666811322/720p60/index-dvr.m3u8

here is the stream analytics link i used: https://twitchtracker.com/ikitty/streams/41427938603

**Comment by ghost** [comment]
@CluelessToaster Works for me.. you sure you are using VLC correctly?

Click Media
Click Open Network Stream
Paste Link
Click Play

**Comment by CluelessToaster** [comment]
Thank you! I was importing it wrong lol
