### ISSUE TITLE
How to use 5--->2 option?

### ISSUE THREAD

**Issue by jeremia314** [TwitchRecover/TwitchRecover#37]
I realised that using 5--->2 option (using twitchtracker link) is the easiest way to recover a VOD. 

But while I was tinkering with the 5--->1 option,( where you have to manually enter all the values ) I have no idea how to enter the starting time of the stream. I tried 
2021-01-18 12:12 
12:12
01-18 12:12     but with no avail....

**Comment by daylamtayari** [comment]
You have to include the seconds value.
So for example, using part of the example you provided, you would enter:
`2021-01-18 12:12:43` (assuming the seconds value here is 43)

**Comment by jeremia314** [comment]
Hmmm.. So how can I get the seconds? I searched Twitchtracker and various other analytics websites but only got until minutes.

**Comment by daylamtayari** [comment]
Twitch Tracker does give you seconds, you simply have to either have js disabled or go to line 8 of the page source.
