### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by Gh0stPlay3r** [TwitchRecover/TwitchRecover#374]
Can someone send me this video? Thanks in advance. 

https://twitchtracker.com/phoenixxvt/streams/40440416329

**Comment by Glyx** [comment]
This VOD contains muted segments. [Here](https://cdn.discordapp.com/attachments/1037435496130941081/1037892289034461274/TwitchRecover-M3U8-2324327.m3u8)'s the file with playable muted segments.
