### ISSUE TITLE
VOD request please

### ISSUE THREAD

**Issue by enarkay** [TwitchRecover/TwitchRecover#375]
I'm trying to download or get the downloadable link for the following stream (less than 24 hours old),
but the program either fails to get the link or just closes itself...

https://streamscharts.com/channels/springsamwol/streams/39824100775

**Comment by ghost** [comment]
@enarkay Doesn't exist.

**Comment by enarkay** [comment]
@ItIckeYd How is that possible? I mean, it's less than a day's old, like I stated above.
Could it be that the streamer didn't erase the vod but set the stream to be not saved as vod in the first place?

**Comment by ghost** [comment]
@enarkay its very possible... twitch is so inconsistent.  Its possible the streamer did not have vod storage enabled but the only way to know is to ask the streamer.

**Comment by enarkay** [comment]
@ItIckeYd I see - thank you anyways for being so kind and volunteering to help out, I really appreciate it :) Hope you have a fantastic day!
