### ISSUE TITLE
VoD Request (It has a page on streamscharts, but not on twitchtracker for some reason)

### ISSUE THREAD

**Issue by WolfRider3000** [TwitchRecover/TwitchRecover#383]
If I use streamscharts link the program just crashes. The link from twitchtracker works, but only shows 140 parts ~ 30 minutes of 3 hours long stream. Is there a way to recover these VoDs https://twitchtracker.com/onigirien/streams/40471193033 or https://streamscharts.com/channels/onigirien/streams/40471315785

There is also a VoD what is less likely to be recovered, as it's almost a month old, but I would appreciate it, if someone will give it a try https://streamscharts.com/channels/onigirien/streams/41363355147

**Comment by ghost** [comment]
@WolfRider3000 

Vod was split into 2 parts.. 

2.5 hour - Vod doesn't exist unfortunately..

23 minute - https://d1m7jfoe9zdc1j.cloudfront.net/94b7b417e24d128557d7_onigirien_40471193033_1668054068/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 140

https://streamscharts.com/channels/onigirien/streams/41363355147 - Vod doesn't exist unfortunately.

**Comment by WolfRider3000** [comment]
Sad, but thank you anyway. It's unfortunate that just because I'm in a different time zone, I have to miss so many fun streams.
