### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by Fortishan** [TwitchRecover/TwitchRecover#384]
Can someone help me please? Thanks! 

https://twitchtracker.com/swaggybark/streams/46284391884

**Comment by ghost** [comment]
@yelloweyedd 

https://d1ymi26ma8va5x.cloudfront.net/74dee22c57b559f917c5_swaggybark_46284391884_1668110412/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 1568
Checking segment 1568/1568... (progress : 100%)
