### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by cyberturiste** [TwitchRecover/TwitchRecover#397]
can someone help with VOD https://streamscharts.com/channels/by_owl/streams/39298104757

**Comment by supp0rter** [comment]
Here's the m3u8 link of your stream:
https://dgeft87wbj63p.cloudfront.net/f4dcd4fa7a2455bd4734_by_owl_39298104757_1670530287/chunked/index-dvr.m3u8

Have fun!

**Comment by cyberturiste** [comment]
ty for help!
