### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by Frenchy872** [TwitchRecover/TwitchRecover#401]
Hey, can someone help me please ? 
https://twitchtracker.com/capassotriplets/streams/47667581053
Thanks a lot !

**Comment by supp0rter** [comment]
https://d2vjef5jvl6bfs.cloudfront.net/8b3470407d895dc6dab8_capassotriplets_47667581053_1671751362/chunked/index-dvr.m3u8 or http://d1m7jfoe9zdc1j.cloudfront.net/8b3470407d895dc6dab8_capassotriplets_47667581053_1671751362/chunked/index-dvr.m3u8

While testing these m3u8 links i got 403 Forbidden errors on muted segments (while downloading), just as a note...

Have fun!

**Comment by Frenchy872** [comment]
Thank you for your help !
