### ISSUE TITLE
Help with a VOD

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#405]
I'm unable to use streamscharts but twitchtracker works, can you check if these VODS are available?

https://streamscharts.com/channels/theboringpharmacist/streams/41664720523

https://streamscharts.com/channels/theboringpharmacist/streams/41664719179

https://streamscharts.com/channels/theboringpharmacist/streams/41664950603

**Comment by Glyx** [comment]
first vod unavailable, 
second vod : https://vod-secure.twitch.tv/ce82cd67c8d2c0d1226c_theboringpharmacist_41664719179_1672406977/chunked/index-dvr.m3u8
third vod unavailable
