### ISSUE TITLE
VOD Recover Help

### ISSUE THREAD

**Issue by George620** [TwitchRecover/TwitchRecover#406]
Can you please help me if it's possible to recover and download this VOD? https://www.twitch.tv/videos/1647601589 It's not loading, but it might be still on the Twitch servers. I had a few VODs of other streamers before that wasn't loading like that. I would like to know if these non-loading VODs are recoverable in some way or it is The End.

**Comment by Glyx** [comment]
just try replacing what twitch recover spits out with "\<url\>/**`index-dvr.m3u8`**" : https://d1m7jfoe9zdc1j.cloudfront.net/bbe99e9f31c898f7e279_barbarousking_47440129965_1667970245/chunked/index-dvr.m3u8

**Comment by George620** [comment]
Thx, it worked! Can I ask how did you get this link if it's not hard?

**Comment by Glyx** [comment]
Well, you'll find that most of Twitch URLs end with `index-dvr.m3u8` so that was just a guess
