### ISSUE TITLE
Help with a vod

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#409]
Hey. sorry to bother you again but can you grab this stream for me since i am unable to, it just shuts down everytime i try to and i dont know how to fix it. i wish this could be fixed since streamcharts is much better than streamtracker, it saves all streams with seperate id's. 

https://streamscharts.com/channels/zoesillss/streams/41689728667

ThankU

**Comment by supp0rter** [comment]
Here you go...

https://dqrpb9wgowsf5.cloudfront.net/5c3a085204efa08f9adc_zoesillss_41689728667_1672987390/chunked/index-dvr.m3u8

Have fun!
