### ISSUE TITLE
VOD Recover Help

### ISSUE THREAD

**Issue by George620** [TwitchRecover/TwitchRecover#410]
I would like to get a downloadable link to this VOD: https://www.twitch.tv/videos/1652526651, because the video isn't loading again. Thx for help.

PS: I still don't get how you get these "Cloudfront" links because I would like to do this myself and not ask for link for every not-loading VOD.

**Comment by Glyx** [comment]
To get the cloudfront link you just have to download Twitch Recover [here](https://github.com/TwitchRecover/TwitchRecover/releases/download/2.0aH/Twitch.Recover.Setup.exe) (or in the [releases](https://github.com/TwitchRecover/TwitchRecover/releases) section), pick option `3`, input your Twitch URL and select your desired quality. 

However, just like issue #406, the CloudFront URL end is weird (don't know why Twitch does this but anyways), so again replace it with `index-dvr.m3u8` and then it should be working : https://d1m7jfoe9zdc1j.cloudfront.net/21165a0bd049ce307872_dgr_dave_47468058317_1668435656/chunked/index-dvr.m3u8

**Comment by George620** [comment]
Oh cool, works again. Thx for everything.

I hope I can do it myself from now on, I swear I tried the option 3 before, I needed to be blind to see the result or thought it was not a link.
