### ISSUE TITLE
VOD req

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#415]
Hi, this link [https://twitchtracker.com/vickypaigexo/streams/47790957725] says 'no vod can be found', can you try and see if it works on streamcharts, much appreciated.

https://streamscharts.com/channels/vickypaigexo/streams/47791234733
https://streamscharts.com/channels/vickypaigexo/streams/47790957725

**Comment by Glyx** [comment]
https://streamscharts.com/channels/vickypaigexo/streams/47791234733
> https://d2vjef5jvl6bfs.cloudfront.net/e795269ed80d1aff1bde_vickypaigexo_47791234733_1673652366/chunked/index-dvr.m3u8


https://streamscharts.com/channels/vickypaigexo/streams/47790957725
> no vod
