### ISSUE TITLE
Vod request

### ISSUE THREAD

**Issue by Goofyahh66** [TwitchRecover/TwitchRecover#417]
Hi.
 I'm having trouble downloading a stream maybe because of it's length (20hours+)
It gives me the NO RESULTS FOUND message and I don't know how to fix it.

Here's the link in case someone can do something about it., 🤞🙂

https://twitchtracker.com/heisuten/streams/47801129101

**Comment by voodoo709** [comment]
Here you go

https://d2vjef5jvl6bfs.cloudfront.net/4dba04d45403a4cb6d16_heisuten_47801129101_1673783414/chunked/index-dvr.m3u8

**Comment by Goofyahh66** [comment]
Sorry to bother you again but i have 2 questions:
1- is what you did simple to do? (I only know how to use twitch recover tho..)
2- the link you gave me stops at 15h53min out of 20h40min and sadly thats pretty much where my obs record stopped.. 😢 Is there a way to get the remaining part of this stream or is it lost in the abysses?

Again, thank you for your time.

**Comment by yassindeb** [comment]
Here are the remaining parts of the stream that you're looking for

1. https://d2vjef5jvl6bfs.cloudfront.net/dc97ba39c21759854a91_heisuten_47806076173_1673840359/chunked/index-dvr.m3u8
2. https://d1m7jfoe9zdc1j.cloudfront.net/c2f0bed5e7faf23248c3_heisuten_47806939133_1673849051/chunked/index-dvr.m3u8

**Comment by Goofyahh66** [comment]
It works idk how you did it but thank you!!

**Comment by yassindeb** [comment]
@Goofyahh66 you just need to use  [https://streamscharts.com/](url) to get the VOD information.
