### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by blublublah** [TwitchRecover/TwitchRecover#428]
Tried this myself but Twitch Recover just closes when I try?

TwitchTracker link: https://twitchtracker.com/fmj_tiger/streams/40877330553
deleted vod Twitch link: https://www.twitch.tv/videos/1728660425

**Comment by ghost** [comment]
@blublublah Doesn't exist.

**Comment by blublublah** [comment]
@Shishkebaboo this stream was just yesterday and he normally saves all his streams.  does this mean he deleted it too quickly, or somehow it's too soon to download it?

**Comment by ghost** [comment]
@blublublah My guess is the streamer deleted it.. or may not have had vod storage turned on. I ran via streamscharts as its the most accurate.

**Comment by blublublah** [comment]
@Shishkebaboo i see.  thanks for taking the time to try help.  appreciate it.
