### ISSUE TITLE
banned vod

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#430]
hey, can you try and grab this stream before its removed from the server. 
https://twitchtracker.com/essie_gotback/streams/41816070187

**Comment by ghost** [comment]
@Arsasses 

https://ds0h3roq6wcgc.cloudfront.net/d4c6bae75a6b31c093e2_essie_gotback_41816070187_1675711689/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 784
