### ISSUE TITLE
VOD req 

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#433]
can you grab this stream https://streamscharts.com/channels/vickypaigexo/streams/41830337419

appreciate it.

**Comment by ghost** [comment]
@Arsasses 

https://vod-pop-secure.twitch.tv/56943d3c2dbb3cdaa657_vickypaigexo_41830337419_1675984541/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
Total Number of Segments: 836
Would you like to check if segments are valid (Y/N): y
Checking segment 836/836... (progress : 100%)
836 of 836 Segments are valid
