### ISSUE TITLE
Vod request

### ISSUE THREAD

**Issue by Mdvilb14** [TwitchRecover/TwitchRecover#442]
Hey I don't have access to twitchRCV and Im also not sure I know how to use it With streamcharts. Could someone give me the links of theses streams please =)

https://streamscharts.com/channels/heisuten/streams/48035700765

https://streamscharts.com/channels/heisuten/streams/48012614605

**Comment by ghost** [comment]
@MgWild14 

https://d1m7jfoe9zdc1j.cloudfront.net/085e62df0b5846af6a68_heisuten_48035700765_1677359025/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
1812 of 1812 Segments are valid


https://d1m7jfoe9zdc1j.cloudfront.net/529bef2a3ec745cb70ce_heisuten_48012614605_1677018834/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
691 of 691 Segments are valid

**Comment by Mdvilb14** [comment]
Tyvm
