### ISSUE TITLE
VOD PLEASE! invalid vod error and crash program

### ISSUE THREAD

**Issue by Kuraffin** [TwitchRecover/TwitchRecover#450]
https://www.twitch.tv/videos/1755456895

**Comment by ghost** [comment]
@Kuraffin 

https://dgeft87wbj63p.cloudfront.net/4881758635438442cde6_kibrisindelisi_39379032645_1677944188/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
4281 of 4281 Segments are valid

**Comment by Kuraffin** [comment]
> @Kuraffin
> 
> https://dgeft87wbj63p.cloudfront.net/4881758635438442cde6_kibrisindelisi_39379032645_1677944188/chunked/index-dvr.m3u8 Vod sessiz segment İÇERMEZ 4281'den 4281'i Segment hakları

How come I can't when you can?

Can you upload this vod in 720p?

I know I asked for a lot, but can you send the link of this in 720p?
https://www.twitch.tv/videos/1756685438

**Comment by ghost** [comment]
@Kuraffin 

https://dgeft87wbj63p.cloudfront.net/4881758635438442cde6_kibrisindelisi_39379032645_1677944188/720p60/index-dvr.m3u8
Vod does NOT contain muted segments
4281 of 4281 Segments are valid


https://d1ymi26ma8va5x.cloudfront.net/39daf76e1eb2bf7556fb_kibrisindelisi_39383252597_1678045819/720p60/index-dvr.m3u8
Vod does NOT contain muted segments
1957 of 1957 Segments are valid

**Comment by Kuraffin** [comment]
> @Kuraffin
> 
> https://dgeft87wbj63p.cloudfront.net/4881758635438442cde6_kibrisindelisi_39379032645_1677944188/720p60/index-dvr.m3u8 Vod sessiz segment İÇERMEZ 4281 Segmentin 4281'i geçerlidir
> 
> https://d1ymi26ma8va5x.cloudfront.net/39daf76e1eb2bf7556fb_kibrisindelisi_39383252597_1678045819/720p60/index-dvr.m3u8 Vod sessiz segment İÇERMEZ 1957 / 1957 Segmentler geçerlidir

**Comment by Kuraffin** [comment]
> @Kuraffin
> 
> https://dgeft87wbj63p.cloudfront.net/4881758635438442cde6_kibrisindelisi_39379032645_1677944188/720p60/index-dvr.m3u8 Vod sessiz segment İÇERMEZ 4281 Segmentin 4281'i hükümler
> 
> https://d1ymi26ma8va5x.cloudfront.net/39daf76e1eb2bf7556fb_kibrisindelisi_39383252597_1678045819/720p60/index-dvr.m3u8 Vod sessiz segment İÇERMEZ 1957 / 1957 Segmentler hakları

thx brother <3
