### ISSUE TITLE
Vod REQ

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#452]
streamcharts doesn't work for me, if you can pull this link https://streamscharts.com/channels/zoesillss/streams/41925222139

appreciate it as always

**Comment by ghost** [comment]
@Arsasses 

https://vod-metro.twitch.tv/329269edbc1faa35186d_zoesillss_41925222139_1678017705/chunked/index-dvr.m3u8
Vod contains muted segments
827 of 827 Segments are valid

Needs to be unmuted.
