### ISSUE TITLE
VOD please

### ISSUE THREAD

**Issue by Julix6** [TwitchRecover/TwitchRecover#454]
https://www.twitch.tv/videos/1747532792

twitchrecover don't work.When I put the stream link, TwitchRecover closes automatically.

**Comment by ghost** [comment]
@Julix6 

https://d1ymi26ma8va5x.cloudfront.net/94e3e60ec1a70d25e0a6_jltomy_40504145752_1677228666/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
13152 of 13152 Segments are valid
