### ISSUE TITLE
Vod req

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#457]
hey brother, a while back i asked for a vod but apparently it was half the vod and i just realized it, i was just able to get half the vod from twitchtracker, maybe you can get the other half from streamscharts, https://streamscharts.com/channels/essie_gotback/streams/41816346283

Appreciate it.

**Comment by ghost** [comment]
@Arsasses 


https://ds0h3roq6wcgc.cloudfront.net/c2bc26bbe89ba65f7665_essie_gotback_41816346283_1675720427/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
522 of 522 Segments are valid

**Comment by Arsasses** [comment]
another one
