### ISSUE TITLE
VOD REQ 

### ISSUE THREAD

**Issue by Unified8** [TwitchRecover/TwitchRecover#458]
https://twitchtracker.com/unified_8/streams/41698921515

https://vod-secure.twitch.tv/9f728c4eff9bad3af3b5_unified_8_41698921515_1673194869/chunked/index-dvr.m3u8

Sun, Jan 8, 08:21
STREAM STARTED
          
Tue, Jan 10, 08:05
STREAM ENDED

Been trying to recover any content from this VOD, it is a couple days over I don't know how many segments are downloadable, help would be appreciated. I have not had much luck when I tried downloading, I have been able to get close but in the end my wifi does not stay connected for long enough to download. If I could recover video without audio this is okay. SO frustrated I did not export this VOD sooner, due to lack of awareness on my part.. 

much love, peace and blessings..!

**Comment by ghost** [comment]
@Unified8 

Enter M3U8 Link: https://vod-secure.twitch.tv/9f728c4eff9bad3af3b5_unified_8_41698921515_1673194869/chunked/index-dvr.m3u8
Checking segments.. 17269 / 17269
0 of 17269 Segments are valid

Unfortunately no video files are available therefore the vod is not downloadable or playable.

**Comment by Unified8** [comment]
unlucky I figured this was the case, thanks for the help yo.. If it could be saved that would have been amazing I am just 1-2 days too late it seems ... STAY SAFE!
