### ISSUE TITLE
SHISHkebab forgive me once more

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#459]
can u get this one https://streamscharts.com/channels/ehmbies/streams/48116391229

**Comment by ghost** [comment]
@Arsasses 

https://d2vjef5jvl6bfs.cloudfront.net/16cefc13d2ff1f3a8235_ehmbies_48116391229_1678577130/chunked/index-dvr.m3u8
Vod contains muted segments

Attached zipped unmuted file.

[VodRecovery_ehmbies_48116391229.zip](https://github.com/TwitchRecover/TwitchRecover/files/10951428/VodRecovery_ehmbies_48116391229.zip)
