### ISSUE TITLE
VLC for m3u8 doesnt work 

### ISSUE THREAD

**Issue by toho00** [TwitchRecover/TwitchRecover#46]
https://vod-secure.twitch.tv/8f819d341af6c70e061f_greekgodx_41605530494_1612634422/720p60/index-dvr.m3u8
there are no muted segments

**Comment by daylamtayari** [comment]
You cant access it because while the playlist file is still up, the actual contents of it, the individual TS files are deleted.
Twitch has been fully deleting a greater percentage of VODs also from their servers when they are deleted by the creator.
Going to update the disclaimer to reflect that.
