### ISSUE TITLE
VOD REQ

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#462]
twitchtracker is the worst, every stream has now two different urls which can only be found on streamscharts one of which can be extracted on twitchtracker. In this case these two streams which i cant grab.

https://streamscharts.com/channels/hexxokami/streams/41946969179
https://streamscharts.com/channels/hexxokami/streams/41947885995

appreciate it once more.

**Comment by ghost** [comment]
@Arsasses  

Neither exist.
