### ISSUE TITLE
VOD REQ

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#468]
i just realized that some streams is not showing up on twitchtracker, can you grab this one 

https://streamscharts.com/channels/aquamoose_/streams/41994050315

Thanks man.

**Comment by ghost** [comment]
@Arsasses 

https://vod-pop-secure.twitch.tv/63b73fd9dc775f5e5d32_aquamoose__41994050315_1679542929/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
972 of 972 Segments are valid
