### ISSUE TITLE
Noob here, trouble recovering deleted VOD

### ISSUE THREAD

**Issue by downloadvodhelp** [TwitchRecover/TwitchRecover#47]
I'm attempting to download a VOD that has been deleted with no success. The VOD is not on twitchtracker or streamcharts, does that mean it's not possible to recover the VOD? I do have the link to the VOD (which no longer works).
Example: https://www.twitch.tv/videos/{UNIQUE_VOD_NUMBERS}

How do I use those the {UNIQUE_VOD_NUMBERS} to retrieve the VOD if it's not on twitchtracker or streamcharts? From what I gathered when reading the README, it seems the numbers at the end of a twitchtracker link will be different than the numbers from the end of a twitch.tv/videos link. Is there no way to convert a dead Twitch VOD link into a twitchtracker/streamcharts link?

Or is there a technical limitation that makes it impossible to download a deleted VOD if all you have is the Twitch VOD link (such as in the above example)? The VOD was just deleted yesterday and I'm using TwitchRecover 2.0 Alpha.

**Comment by daylamtayari** [comment]
I would strongly recommend also checking out Sully Gnome (https://sullygnome.com) to see if you can find the stream there and if you do, you can then input the values manually. 

With only the VOD ID and not the Stream ID there is no way to recover the VOD as there is no way to retrieve any information about a VOD ID (i.e. which channel, when it was made, etc.), whether it is from the APIs or using third party data sources, if that VOD has been deleted.

**Comment by Adroxxx** [comment]
How to I proceed if the stream is on sullygnome??

**Comment by daylamtayari** [comment]
@Adroxxx You get the values and input them manually, selecting the manual input option.
