### ISSUE TITLE
Vod please

### ISSUE THREAD

**Issue by Julix6** [TwitchRecover/TwitchRecover#471]
https://twitchtracker.com/jltomy/streams/39441602517

https://www.twitch.tv/videos/1774495882

**Comment by IlanZ93** [comment]
LMAO, not a word only a title and link ?
Manage on your own, we are not robots.

There is a Discord and Tuto on it.

**Comment by longusnickus** [comment]
browser addon: TwitchNoSub

**Comment by ghost** [comment]
@Julix6 

https://d1ymi26ma8va5x.cloudfront.net/02b5ed435fdfe516d813_jltomy_39441602517_1679774160/chunked/index-dvr.m3u8
Vod does NOT contain muted segments

@IlanZ93 I don't think that comment was really necessary but whatever floats your boat.

**Comment by IlanZ93** [comment]
@Shishkebaboo There is all the information on this Git or on the discord & even on your git so that people can manage on their own, if they have a problem there is the Discord, that's what I did too .

So when someone asks without trying, they can at least remain human and not just say "VOD PLEASE $link $link".

If it makes you happy to do all the requests of ill-mannered people, good for you.

**Comment by ghost** [comment]
@IlanZ93 I think your exaggerating this quite a bit.. you do realize it takes me less then 5 seconds to do any request... not only that but I do it when I have free time so its not affecting my life at all. I think people understand that someone might or might not get back to them.. its a risk they take by not taking the time to learn how to install/run the application.

I think commenting negitively towards other users just to comment is a waste and a bad look... why say anything if its not going to be helpful. I mean if thats what you want to do... going to be a lot more issues to comment negitively on... better get to work.

**Comment by IlanZ93** [comment]
Yes it take less than 5 second, but to type "Hello can you help me for this vod : $link $link" don't take more time.

Thats not the first time : https://github.com/TwitchRecover/TwitchRecover/issues/454

Not even a thank you. I mean is this a lot to ask to be polite just a little lol ?

**Comment by ghost** [comment]
@IlanZ93 Them not saying please is equal to you commenting negitively so your equal... happy? I mean there is no problem here you are complaining about something so miniscule its not even worth discussing. 

If I decide to retrieve the vod.. that is my decision. If they decide to make an issue that is their decision what gives you the right to comment negitively or demand things.

**Comment by Julix6** [comment]
> @Julix6
> 
> https://d1ymi26ma8va5x.cloudfront.net/02b5ed435fdfe516d813_jltomy_39441602517_1679774160/chunked/index-dvr.m3u8 Vod does NOT contain muted segments
> 
> @IlanZ93 I don't think that comment was really necessary but whatever floats your boat.
