### ISSUE TITLE
Vod please 

### ISSUE THREAD

**Issue by Julix6** [TwitchRecover/TwitchRecover#473]
when i do it it doesn't work     thanks in advance

https://twitchtracker.com/jltomy/streams/40594102360

**Comment by ghost** [comment]
@Julix6 

https://d1ymi26ma8va5x.cloudfront.net/58a603d427bc7baf1560_jltomy_40594102360_1679689070/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
2719 of 2719 Segments are valid
