### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by Yoannmont** [TwitchRecover/TwitchRecover#481]
Hello, I'm unable to download or get the link to this VOD because program crashes : https://www.twitch.tv/videos/1788927386

**Comment by ghost** [comment]
https://d1ymi26ma8va5x.cloudfront.net/5f05d8e4dfb40c2ca43f_kidlonni_46773678476_1681030834/chunked/index-dvr.m3u8
Vod contains muted segments
2014 of 2014 segments are valid (100.00% of the VOD available)

Attached unmuted file

[VodRecovery_kidlonni_46773678476.zip](https://github.com/TwitchRecover/TwitchRecover/files/11193683/VodRecovery_kidlonni_46773678476.zip)

**Comment by Yoannmont** [comment]
Thanks a lot
