### ISSUE TITLE
VOD PlS

### ISSUE THREAD

**Issue by Kagama1** [TwitchRecover/TwitchRecover#487]
Can someone give me these vod links pls :

https://m.twitch.tv/videos/1795587716

https://m.twitch.tv/videos/1796411252

**Comment by ghost** [comment]
@Kagama1 

Need twitchtracker or streamscharts link

**Comment by Kagama1** [comment]
https://twitchtracker.com/aminematue/streams/46794961612
https://twitchtracker.com/aminematue/streams/46797232796
Thx

**Comment by ghost** [comment]
@Kagama1 

https://d1ymi26ma8va5x.cloudfront.net/736e774a28c1d4a41a1b_aminematue_46794961612_1681672175/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
2066 of 2066 segments are valid (100.00% of the VOD available)

https://dgeft87wbj63p.cloudfront.net/9b3a24c0fcb4c38ddfb8_aminematue_46797232796_1681758783/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
2545 of 2545 segments are valid (100.00% of the VOD available)

**Comment by Kagama1** [comment]
Thx bro
