### ISSUE TITLE
having trouble with a certain stream

### ISSUE THREAD

**Issue by Mdvilb14** [TwitchRecover/TwitchRecover#495]
Hey, im having a hard time getting the link or unmuted file of this stream: 

when i use streamcharts , TwitchRec closes itself. https://streamscharts.com/channels/heisuten/streams/42109244043

when i use twitchtracker and then unmute it, i am left with only 5min of the stream (of 3hours stream). https://twitchtracker.com/heisuten/streams/48354614461.

Anyone to help me? >:)

edit: if you have a way to fetch the link please gimme medium quality link (720p)

**Comment by KaMyKaSii** [comment]
Use this link on your player: http://sprunge.us/ys3kVS
