### ISSUE TITLE
Cannot play muted audio sections of the vod

### ISSUE THREAD

**Issue by mysteriarch** [TwitchRecover/TwitchRecover#5]
Twitch vod link: https://www.twitch.tv/videos/824670908 (muted audio parts 4:42:00 to 4:47:30)
m3u8 link: https://dqrpb9wgowsf5.cloudfront.net/26cb4ba6b97de685e57d_xqcow_40802135886_1607035556/chunked/index-dvr.m3u8

Skipping to the muted audio part in VLC will show this error message:

![unknown](https://user-images.githubusercontent.com/59431551/101163363-5d5d1c00-35e8-11eb-8bbd-e803d90e5442.png)

**Comment by daylamtayari** [comment]
In order to get a muted segment, replaced the `-unmuted.ts` part of the muted segment to `-muted.ts` and it will work fine.

**Comment by daylamtayari** [comment]
TODO: Setup a way to automatically convert a VOD with muted segments into a vod with no muted segments.

**Comment by daylamtayari** [comment]
Successfully recovered the unmuted VOD in its entirety.
Attached is the working m3u8.

**Comment by daylamtayari** [comment]
While you can recover the video of the muted segments, you cannot recover the audio. You cannot recover the audio from segments that are muted. That is a limit on Twitch's end and there are no existing tools or methods to recover the audio from segmented segments.
Thus, this tool will recover the video segments of the m3u8 so you can watch the entirety of the VOD but will still not hear the audio from muted segments.

**Comment by daylamtayari** [comment]
This feature will be automatically implemented in the download feature which will be a new part of the 2.0 release.
