### ISSUE TITLE
Instant crash (?) when using 4th option

### ISSUE THREAD

**Issue by teisseire117** [TwitchRecover/TwitchRecover#50]
Using option 4. Download a VOD (including sub-only). Then writing the link to the VOD : twitch.tv/videos/399720927

Instantly close the command prompt, and nothing else happens. Am I doing something wrong ? I tried 2.0 with hotfix.

**Comment by N3ars** [comment]
That's a highlight, you have to choose the option 7.

**Comment by teisseire117** [comment]
> That's a highlight, you have to choose the option 7.

Ohh... I'm sorry
