### ISSUE TITLE
VOD 

### ISSUE THREAD

**Issue by Mdvilb14** [TwitchRecover/TwitchRecover#521]
Hey i only get the first half of this stream when i use a twitchtracker link 

and i still dont know how to use streamcharts.. @_@   could someone do it for me , heres the link of the missing part:

https://streamscharts.com/channels/heisuten/streams/48554962989   ( in720/1080p)

**Comment by KaMyKaSii** [comment]
https://d1m7jfoe9zdc1j.cloudfront.net/36d7537916975db75f22_heisuten_48554962989_1685138818/chunked/index-dvr.m3u8

**Comment by Mdvilb14** [comment]
Amazing tyvm
