### ISSUE TITLE
Hard one to recover

### ISSUE THREAD

**Issue by Mdvilb14** [TwitchRecover/TwitchRecover#537]
Hey I posted a request of links for 2 streams that twitchtracker.com can't back up under jeremy876 's request but I'm not sure anyone has seen it. 
So here' s a copy of it so I can get more visibility (please don't see this as eager/impatience🙂) 

"
The problem for me is that TwiRecov keeps closing when I use a streamscharts link. (5-1 command)

Here are the streams that I (we?) want to get:

https://streamscharts.com/channels/heisuten/streams/48661676877

https://streamscharts.com/channels/heisuten/streams/48661880573

https://streamscharts.com/channels/heisuten/streams/48669124877

https://streamscharts.com/channels/heisuten/streams/48669281101

https://streamscharts.com/channels/heisuten/streams/48674558397

thank you for your time helping us "

**Comment by owk880301** [comment]
https://d1m7jfoe9zdc1j.cloudfront.net/ab415acdf23a9a3338ab_heisuten_48661676877_1686525452/chunked/index-dvr.m3u8

https://d1m7jfoe9zdc1j.cloudfront.net/b92453c9dc9a8a584a86_heisuten_48661880573_1686526932/chunked/index-dvr.m3u8

https://d1m7jfoe9zdc1j.cloudfront.net/072cb2467a26e262b450_heisuten_48669124877_1686611274/chunked/index-dvr.m3u8

https://d1m7jfoe9zdc1j.cloudfront.net/56594f481132bdbfc2f9_heisuten_48669281101_1686612449/chunked/index-dvr.m3u8

https://d1m7jfoe9zdc1j.cloudfront.net/278aa888ad85beffc4a6_heisuten_48674558397_1686683629/chunked/index-dvr.m3u8

**Comment by Mdvilb14** [comment]
That's very nice of you.

I think someone had given me an explanation for this.. I need to check my old issues.
