### ISSUE TITLE
IMPORTANT VOD REQ

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#540]
can you grab this vod for me. https://streamscharts.com/channels/stridsvagnes/streams/42325039675
its not on twitchtracker. just streamscharts.

Appreciate it.

**Comment by owk880301** [comment]
https://vod-secure.twitch.tv/8b0664c3432136e87092_stridsvagnes_42325039675_1686842811/chunked/index-dvr.m3u8
