### ISSUE TITLE
VOD Recover (with a issue)

### ISSUE THREAD

**Issue by JenkoSII** [TwitchRecover/TwitchRecover#544]
Link : https://twitchtracker.com/jamel_le_chomeur/streams/39688113381

**Comment by owk880301** [comment]
https://dgeft87wbj63p.cloudfront.net/562fae946c982b50c70c_jamel_le_chomeur_39688113381_1687025910/chunked/index-dvr.m3u8

**Comment by JenkoSII** [comment]
thx

**Comment by JenkoSII** [comment]
it's not the same VOD because I noticed that on the stream in question in twitchtracker it's not the one I want
I wanted the lastest stream of Jamel_le_chomeur

**Comment by ghost** [comment]
@JenkoSII You need to send the link of the vod you want... its hard for us to guess which one it is.

**Comment by JenkoSII** [comment]
Oui je sais mais le fait est que quand j'envoie le lien de la VOD c'est celui d'une autre VOD mais bon ce n'est pas grave j'ai une autre que je veux récupérer : https://twitchtracker.com/jamel_le_chomeur/streams/40822006472

**Comment by JenkoSII** [comment]
Yes, I know, but the fact is that when I send the VOD link it's for another VOD, but it doesn't matter, I've got another one I want to get : https://twitchtracker.com/jamel_le_chomeur/streams/40822006472

**Comment by ghost** [comment]
@JenkoSII 

https://d1ymi26ma8va5x.cloudfront.net/5b48a806e92db97b8140_jamel_le_chomeur_40822006472_1687199575/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
1731 of 1731 segments are valid. (100.00% of the VOD is available)

**Comment by JenkoSII** [comment]
thx you were quick
