### ISSUE TITLE
Pls help me get this vod

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#565]
can you grab this one for me, its a split stream https://streamscharts.com/channels/gabmichelle/streams/48878768493

always appreciated.

**Comment by zerorngzer0** [comment]
[https://d2vjef5jvl6bfs.cloudfront.net/c47ba5bb0cf26d8dcbb3_gabmichelle_48878768493_1689511428/chunked/index-dvr.m3u8](url)
