### ISSUE TITLE
Anyone who can get this VOD

### ISSUE THREAD

**Issue by Arsasses** [TwitchRecover/TwitchRecover#568]
i can't get this vod because its split into five section, i was able to get one of them from twitchtracker, any chance you can get this
https://streamscharts.com/channels/jasmingronski/streams/42515126875

thanks

**Comment by owk880301** [comment]
https://vod-secure.twitch.tv/33e0c27d8e1d5df6946b_jasmingronski_42515126875_1690446769/chunked/index-dvr.m3u8

**Comment by Arsasses** [comment]
thank you sir
