### ISSUE TITLE
Help with VOD

### ISSUE THREAD

**Issue by L3xisaurus** [TwitchRecover/TwitchRecover#597]
I tried to use the app but everytime i paste the link and hit enter it crashes. My broadcast somehow got deleted during stream and it has memories with my kiddo I can't get again. I'm hoping it's somewhere in the twitch space. If someone could please help me that would be amazing!

https://streamscharts.com/channels/l3xisaurus_/streams/42169170777

**Comment by ghost** [comment]
@L3xisaurus 

[VodRecovery_l3xisaurus__42169170777.zip](https://github.com/TwitchRecover/TwitchRecover/files/13804093/VodRecovery_l3xisaurus__42169170777.zip)

Some segments are not available therefore I had to attach a file rather then a basic link.

**Comment by Demon1342** [comment]
@Shishkebaboo How were you able to recover this VOD? Neither TwitchRecover nor VodRecovery seem to work anymore

**Comment by Shishkebaboo** [comment]
@L3xisaurus VodRecovery still works for me and is likely to continue to do so unless Twitch changes their method of creating m3u8 playlists, which seems unlikely. If for whatever reason website recovery doesn't work for you.... (probably cloudfare bot detection), manual recovery remains a viable option, provided that the VOD still exists in the server.

**Comment by L3xisaurus** [comment]
I actually found a work around using google chrome and an extension..what a lifesaver..i do appreciate the help! :D
