### ISSUE TITLE
Would it be possible to recover this VOD please?

### ISSUE THREAD

**Issue by dolphinXDD** [TwitchRecover/TwitchRecover#606]
Hello
Can I get this VOD back?

[link](https://twitchtracker.com/homete416/streams/40894414103)
Thanks.

**Comment by expectaccesviolation** [comment]
![6JZZxaAopq](https://github.com/TwitchRecover/TwitchRecover/assets/155553732/352fb29c-043e-47dd-ac27-af62efd599fa)

**Comment by dolphinXDD** [comment]
So sad😢
But thank you.
