### ISSUE TITLE
Question - Is there another twitch tracking website you can add to options?

### ISSUE THREAD

**Issue by SamuraiThomas** [TwitchRecover/TwitchRecover#61]
The two current ones have their big probelms.
Twitchtracker is using a captcha so the program crashes when their links are inputted.
Streamcharts has completely revamped their website and now only seem to allow viewing of streams from Feb 12, or so. Otherwise you must pay like 300$ a month just to see stream details.
https://streamscharts.com/pricing
wtf. And probably, if the subsciption was actually reasonable, you'd have to implement a login system.

**Comment by daylamtayari** [comment]
Twitch Tracker **has not** implemented a captcha and the program does not crash when you import them.
Streamscharts allows you to get the stream page (which is all you need), some stream details, and also all of the streams for the past 30 days without a subscription. 

If you have another website that you want me to add feel free to create an issue suggesting it but these two websites do not have any issues breaking them or preventing users from using them to the necessary level without a subscription.

**Comment by SamuraiThomas** [comment]
![2021 02 19-15 03 (2)](https://user-images.githubusercontent.com/63924624/108521565-c6892d00-72c3-11eb-83ef-9de408963c7c.png)
My bad. While twitchtracker does have a captcha, it's only when using a vpn. WIthout vpn it works fine
