### ISSUE TITLE
Can you help me recover this video? 

### ISSUE THREAD

**Issue by FelCombaud** [TwitchRecover/TwitchRecover#623]
Hello, 
I can't recover this video with the actual tool (1.2 and 2.0) as the soft crash when I submit the url to recover.

https://twitchtracker.com/danycaligula/streams/40441557685

Is there an trick?

**Comment by MacielG1** [comment]
https://dgeft87wbj63p.cloudfront.net/f91c1861950336539eae_danycaligula_40441557685_1707784683/chunked/index-dvr.m3u8

**Comment by FelCombaud** [comment]
> https://dgeft87wbj63p.cloudfront.net/f91c1861950336539eae_danycaligula_40441557685_1707784683/chunked/index-dvr.m3u8

Many thanks for the answer ! 
Can you help me to know how you get .m3m8 file ? I see the options in Twitch Recover but can manage to have a link like you !

**Comment by MacielG1** [comment]
If Twitch Recover doesn't work, try using VodRecovery
