### ISSUE TITLE
Monitor a streamer status and record it whenever the channel is live? [enhancement]

### ISSUE THREAD

**Issue by antonioExpositoRodriguez** [TwitchRecover/TwitchRecover#63]
Hi, now that Twitch is deleting the vods and they can't be recovered anymore, could it be possible to add this feature? To leave the program running while it checks a channel status and start recording when it goes live? I know to download a live stream is projected for 2.0 beta, but I don't know if it will have the option to leave it running in the background. I've seen a few python scripts with that purpose but couldn't make them work. I don't know if it's possible or you are interested in it, anyway thanks for your work.

**Comment by daylamtayari** [comment]
In the beta there will be an option to download live streams as they are happening and that can run in the background just fine, it will only take up the bandwidth needed to download the desired quality.
If you are talking about making a program that just continuously scans for if the channel goes live and then immediately start downloading, that is not something that is in the works and if anything I would make a separate program for that if I get some demand for it.

**Comment by daylamtayari** [comment]
In the meantime, if you want to be able to download live streams as they are happening, download `youtube-dl` and `ffmpeg`, add both of them to your system path (add the location of the two exe's to your system path environment variable).
Then create a new batch file (i.e. `TwitchDownload.bat`) and then paste the following lines in it:
```bat
for /f "delims=" %%a in ('youtube-dl -f best -g https://www.twitch.tv/[channel name]') do (ffmpeg -i %%a -c copy download.ts)
pause
```
Change the channel name to the channel you are looking to download the stream from and then just run it. 
This is a very rudimentary method but works.

**Comment by antonioExpositoRodriguez** [comment]
> 
> 
> If you are talking about making a program that just continuously scans for if the channel goes live and then immediately start downloading, that is not something that is in the works and if anything I would make a separate program for that if I get some demand for it.

Yeah, that was what I was hoping for, for those streams that I can't catch live and are later deleted the only way I could watch them later would be recording them myself live but often they are on when EU is asleep so... As I said, even if is not in the works or in the future for the app, thanks for the work that you have already put in it.

P.D.:... and sorry for my poor English.

**Comment by daylamtayari** [comment]
No problem and yeah that is something I would make into a separate program since it would need to be a program constantly running in the background and that is not something I want Twitch Recover to be. 
The program itself should be pretty simple to make since all it needs to do is check if a channel is live and if so, launch the recording.  
I will work on it in the near future especially since it should not be particularly complicated, probably after Twitch Recover 2.0 is released.
I will inform you here whenever I am finished with it and if you want to stay informed of my future projects, feel free to follow me on Github.

**Comment by daylamtayari** [comment]
But I really like that idea since I am friends with quite a few EU folks who miss streams and are unable to watch the missed VODs because they either got deleted or were not saved and this would be a very useful solution.

**Comment by antonioExpositoRodriguez** [comment]
> 
> 
> But I really like that idea since I am friends with quite a few EU folks who miss streams and are unable to watch the missed VODs because they either got deleted or were not saved and this would be a very useful solution.

I'm glad you liked the idea, I've just followed you and hopefully you have the time/drive to make such a program in the future. Thank you very much.

**Comment by wl03355609** [comment]
> In the meantime, if you want to be able to download live streams as they are happening, download `youtube-dl` and `ffmpeg`, add both of them to your system path (add the location of the two exe's to your system path environment variable).
> Then create a new batch file (i.e. `TwitchDownload.bat`) and then paste the following lines in it:
> 
> ```batchfile
> for /f "delims=" %%a in ('youtube-dl -f best -g https://www.twitch.tv/[channel name]') do (ffmpeg -i %%a -c copy download.ts)
> pause
> ```
> 
> Change the channel name to the channel you are looking to download the stream from and then just run it.
> This is a very rudimentary method but works.

Is there any Mac relevant command for it?
I've tried youtube-dl -f best -g https://www.twitch.tv/[channel name] -o test.mp4 but the link is not the same as the one just use youtube-dl -f best -g https://www.twitch.tv/[channel name] so it failed
