### ISSUE TITLE
can you help me recover thoses VODs pls ?

### ISSUE THREAD

**Issue by NinaCal** [TwitchRecover/TwitchRecover#638]
hi ! 
can you please help me recover those vods ?

https://twitchtracker.com/aminematue/streams/42503753785
https://twitchtracker.com/aminematue/streams/44009674235

thank you so much !

**Comment by expectaccesviolation** [comment]
https://d1m7jfoe9zdc1j.cloudfront.net/45153bf9b674904ce785_aminematue_42503753785_1712861742/chunked/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/0f954f2c1aed18eeda4d_aminematue_44009674235_1712948406/chunked/index-dvr.m3u8

**Comment by NinaCal** [comment]
thank youuu
