### ISSUE TITLE
No VOD found on Twitch servers for a stream that is still live

### ISSUE THREAD

**Issue by jonas1015119** [TwitchRecover/TwitchRecover#644]
@Shishkebaboo any ideas? never had this happen before even with deleted stream, the previous two ones worked fine.

https://twitchtracker.com/billzo/streams/44142928347

**Comment by ghost** [comment]
@jonas1015119 

First half hour:
https://d2nvs31859zcd8.cloudfront.net/3765784632c4226e8a55_billzo_44142709035_1714850557/chunked/index-dvr.m3u8
Video does NOT contain muted segments
Checking segments.. 158 / 158
158 out of 158 Segments are Available.

Next part of stream (Vod ID you asked for):
https://ds0h3roq6wcgc.cloudfront.net/78be780ac40a8155339f_billzo_44142928347_1714852179/chunked/index-dvr.m3u8
Video does NOT contain muted segments
Checking segments.. 1352 / 1352
1352 out of 1352 Segments are Available.

Recovery is dependent on the start time as you can see below twitchtracker is off by quite a bit:

Streamscharts: Start Time: 04 May 2024, 19:49
TwitchTracker: Start Time: 04 May 2024, 20:45

I would recommend using streamscharts the majority of the time for accuracy.

**Comment by jonas1015119** [comment]
@Shishkebaboo 
thanks you!
Yeah TwitchTracker seems to have some issues with these marathon streams, it doesnt like the 48h cutoffs.
VODRecovery managed to get the second ID (though with a "https://vod-metro.twitch.tv/" based link instead of the cloudfront one, any idea why that is?), but I would have missed the first part.
