### ISSUE TITLE
Help to recover this VOD

### ISSUE THREAD

**Issue by Takois** [TwitchRecover/TwitchRecover#649]
https://streamscharts.com/channels/alphamariox/streams/44242543739

**Comment by ghost** [comment]
@Takois 

https://vod-metro.twitch.tv/bd09a317afc2de8e9dfc_alphamariox_44242543739_1716548274/chunked/index-dvr.m3u8
Video does NOT contain muted segments
Checking segments.. 800 / 800
800 out of 800 Segments are Available.
