### ISSUE TITLE
VOD cannot be found on twitch's servers?

### ISSUE THREAD

**Issue by TBloop** [TwitchRecover/TwitchRecover#66]
I'm attempting to recover a VOD that was deleted. Here is the streamscharts and twitchtracker links to the broadcast. The streamer deleted the VOD, and then continued streaming. Confusingly, on twitchtracker, it doesn't create 2 different pages, its just the same link for the entire day. (I've seen this happen before). 

Anyway, i'm trying to get the deleted VOD recovered, but it says it cant find the VOD on twitch servers. I tried using both links below. Also, I tried retrieving the link to the VOD right before it was deleted (or maybe it was deleted already?) and I recall the link ended in deleted-index.m3u8, or something similar with 'deleted' in the name, and it wouldn't open in VLC.

Has something changed on twitch to stop us from doing this, or is this a one-off issue? I hope they haven't patched this tool!

https://streamscharts.com/twitch/channels/nickykittyxx/streams/41803766382
https://twitchtracker.com/nickykittyxx/streams/41803766382
https://www.twitch.tv/videos/924515512

Any help is much appreciated.

**Comment by daylamtayari** [comment]
Streamscharts did create two different pages: 
https://streamscharts.com/twitch/channels/nickykittyxx/streams/41803766382 and https://streamscharts.com/twitch/channels/nickykittyxx/streams/41803766382
However, for the first VOD, it cannot be found. Twitch has started actively fully deleting most deleted VODs. This is a move on Twitch's end and which affects most but not all channels.
