### ISSUE TITLE
Problem recovering a deleted vod

### ISSUE THREAD

**Issue by Oidocrop9999** [TwitchRecover/TwitchRecover#67]
I'm trying to recover this vod as usual. I've tried all the different versions and modes to do it but there seems to be no way to get it back. Is there anyone who can help me? Thanks

https://twitchtracker.com/ilgabbrone/streams/41199102252

**Comment by daylamtayari** [comment]
The VOD for this stream cannot be found.
I tried it on my end too and could not find it, the VOD is not available on Twitch VOD servers, there is nothing you can do about it.
