### ISSUE TITLE
.m3u8 file found but doesn't work

### ISSUE THREAD

**Issue by luieti** [TwitchRecover/TwitchRecover#69]
I'm attempting to recover a vod from 30 days ago using Option 5 and a streamcharts link. The program gives me a link to download a .m3u8 file which I have attempted to open with VLC media player unsuccessfully. I also tried using VLC to convert the file to a .mp4 and this process happens instantly and produces an empty/corrupt .mp4 file. 

Any advice? It seems strange the program would successfully produce a link to a file that ends up only being like 12KB.

**Comment by luieti** [comment]
This was using the 2.0 alpha version of the program. I tried 1.2 as well and had the same results.

**Comment by daylamtayari** [comment]
The M3U8 is a playlist file not a video file, to open it, you have to copy paste the M3U8 link and paste it into VLC.

Please see the GIF below for how to open it in VLC.

![](https://camo.githubusercontent.com/3eb55bd6198552b568aaeded422bd52a2fb49336c15af232c30ca6b5e50c785d/68747470733a2f2f692e6779617a6f2e636f6d2f38646538393736333031353835326330616237306161626336343437656330342e676966)
