### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by teisseire117** [TwitchRecover/TwitchRecover#70]
Hi,

I'm looking for the stream IDs of a twitch channel from January to August 2015. Sullygnome only goes back until August 2015 but no further.

Thank you 
(I was thinking, maybe it would be possible to get the channel name of a stream ID and then check all stream IDs to find the ones from a particular channel ?)

**Comment by daylamtayari** [comment]
There are no websites that are still up today that track streams from prior to August 2015.

You cannot reverse engineer stream IDs from a channel name.
Stream IDs are purely incremental.
Whenever someone goes live and the new stream ID is calculated, it simply adds 1 to the last stream ID, the channel name or ID has no effect whatsoever on the stream ID.
