### ISSUE TITLE
Can't play not-muted .m3u8

### ISSUE THREAD

**Issue by penguin0616** [TwitchRecover/TwitchRecover#76]
The link in question: https://vod-secure.twitch.tv/2a650949ee635556903a_kleientertainment_41839294990_1614295568/720p60/index-dvr.m3u8

The program says "M3U8 DOES NOT contain any muted segments."
I am still unable to open the program with VLC.
When attempting to do an unmute, just in case, the program crashes.

**Comment by daylamtayari** [comment]
This is because while the playlist link is still up the individual files are deleted. 
Please see this issue post for more details: #68 .
