### ISSUE TITLE
How does option 15 work if deleted VODs are permanently gone?

### ISSUE THREAD

**Issue by kimsoohyung** [TwitchRecover/TwitchRecover#78]
I read and understand the issue explained on #68, but I was curious about how "Recover ALL clips (option 15)" works as it seems like it's able to cycle through the deleted VOD to trace down the clip files.

**Comment by daylamtayari** [comment]
Option 15 does not go through a deleted VOD to find the clips, the clips are independent of the VOD.
The long term file naming format of clips is the following: `https://clips-media-assets2.twitch.tv/[stream id]-offset-[offset number].mp4`.
With the stream ID we are then able to brute force all of the possible offset number values thus all of the clips of that stream available with that file format.
