### ISSUE TITLE
M3U8 Video Not Playing

### ISSUE THREAD

**Issue by ProcrastShill** [TwitchRecover/TwitchRecover#83]
Used option 9, found muted segments. Used option 10, video still comes up with a blank screen.

**Comment by daylamtayari** [comment]
What is the m3u8 link?

**Comment by Andioxt** [comment]
I also had a similar problem trying to recover this vod https://twitchtracker.com/onc_tournaments/streams/40743088462 
This vod had muted segments so I used option 10 to unmute those parts and got a m3u8 file which I put back into VLC player as a file but it still wouldn't open.

**Comment by ProcrastShill** [comment]
Base m3u8 link: https://vod-secure.twitch.tv/8ebce379d6cea34ad0a9_roachevr_41245185182_1610155774/chunked/index-dvr.m3u8
Unmuted m3u8 file can't be attached to this post, so you'll have to unmute it yourself.

**Comment by Andioxt** [comment]
I'm aware of how to get the base m3u8 link it's just that once I get the unmuted file called TwitchRecover-M3U8-9679081 I can't open it in VLC. (Black screen) Maybe its because im opening it as a file but I don't really know how to get a link out of it and how that would make a difference.

**Comment by ProcrastShill** [comment]
> I'm aware of how to get the base m3u8 link it's just that once I get the unmuted file called TwitchRecover-M3U8-9679081 I can't open it in VLC. (Black screen) Maybe its because im opening it as a file but I don't really know how to get a link out of it and how that would make a difference.

I was replying to Daylamtayari.

**Comment by Andioxt** [comment]
> > I'm aware of how to get the base m3u8 link it's just that once I get the unmuted file called TwitchRecover-M3U8-9679081 I can't open it in VLC. (Black screen) Maybe its because im opening it as a file but I don't really know how to get a link out of it and how that would make a difference.
> 
> I was replying to Daylamtayari.

mb kinda got lost with the comments. Forgot that this was your thread.

**Comment by daylamtayari** [comment]
@Andioxt @ProcrastShill Looked at both of your issues and you both have the exact same issue.
While the M3U8 playlist link is still retrievable, the actual video files that you are trying to retrieve have all being deleted so when you are trying to play it, its trying to retrieve and play video files that don't exist.
Please refer to #68 for more details. 
There is nothing that can be done since the video files have being fully deleted.
