### ISSUE TITLE
Can't you set the storage space to where you want it?

### ISSUE THREAD

**Issue by asdadadada1213** [TwitchRecover/TwitchRecover#89]
When you recover with Twitch Recover, you'll see which storage space you'll download, but there's no storage space on drive c, so I set it to drive E, but it'll go down to drive c. Can't you set the storage space to where you want it?

**Comment by daylamtayari** [comment]
So how it currently works is that it will download the files in your temp directory which by default is on your C drive and then will piece together the files into the final VOD, save that where you wanted, thus drive E in your case and then delete the files on the C drive. 
This is something that I am aware of and that will be changed in the beta.
In the beta, all of the files will be directly downloaded in the directory that you want your output file to be in.
