### ISSUE TITLE
Download stream and chat of live only?

### ISSUE THREAD

**Issue by churrodude666** [TwitchRecover/TwitchRecover#92]
Hi, for streamers who don't have their live streams set to archive, would it be possible to download the video from start to end after it's finished, along with the chat?

I don't think this is a exact duplicate, but if it is I'll close the issue. Would be awesome, like the script is already 😀

**Comment by daylamtayari** [comment]
No you cannot. If a streamer does not archive/turn their VODs on, no VOD of the stream will ever be made available in a publicly accessible server so you cannot go and view the VOD or download it.

**Comment by daylamtayari** [comment]
I did forget to add, a feature to be able to download livestreams live as they are occuring will soon be added.
