### ISSUE TITLE
5. Recover a VOD is not available.

### ISSUE THREAD

**Issue by sltzh54** [TwitchRecover/TwitchRecover#94]
Entering the address of the Twitch Tracker to use the feature will immediately close the program.

**Comment by antisad** [comment]
There's problem with Twitch tracker links. Use Streamscharts links

**Comment by daylamtayari** [comment]
It is indeed an issue with Twitch Tracker links following them adding something to prevent automated, bot like requests.
In the meantime, please utilise streams charts or input the info manually.
